# api:
#   enabled: false
#   address: 0.0.0.0:8686

sources:
  docker_logs:
    type: docker_logs
    exclude_containers:
      - "vector"
      - "swarmpit"
      - "traefik"

  traefik_logs:
    type: "docker_logs"
    include_containers:
      - "traefik"

transforms:
  traefik_logs_decode:
    type: remap
    inputs: ["traefik_logs"]
    source: |-
      .access_data = parse_json!(.message)


sinks:
  docker_logs_sink:
    type: "aws_cloudwatch_logs"
    inputs: ["docker_logs"]
    compression: "gzip"
    encoding:
      codec: "json"
    region: "us-east-2"
    group_name: "/vector/docker-logs"
    stream_name: {{ "\"{{ host }}\"" }}
    auth:
      access_key_id: "{{ env "AWS_ACCESS_KEY_ID" }}"
      secret_access_key: "{{ env "AWS_SECRET_ACCESS_KEY" }}"
    healthcheck: false

  traefik_access_sink:
    type: "aws_cloudwatch_logs"
    inputs: ["traefik_logs_decode"]
    compression: "gzip"
    encoding:
      codec: "json"
    region: "us-east-2"
    group_name: "/vector/traefik"
    stream_name: {{ "\"{{ host }}\"" }}
    auth:
      access_key_id: "{{ env "AWS_ACCESS_KEY_ID" }}"
      secret_access_key: "{{ env "AWS_SECRET_ACCESS_KEY" }}"
    healthcheck: false

  # debug:
  #   type: "console"
  #   inputs: ["traefik_logs"]
  #   encoding:
  #     codec: "text"
