version: "3.8"

services:
  mapping-client:
    image: registry.radartoolkit.com/mapping-client:latest
    networks:
      - traefik_public
    environment:
      - NODE_ENV=prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mapping-client-app.rule=Host(`mapping.radartoolkit.com`) || Host(`broadbandmapping.com`) || Host(`broadbandmapping.org`) || Host(`broadbandmapping.net`) || Host(`www.broadbandmapping.com`) || Host(`www.broadbandmapping.org`) || Host(`www.broadbandmapping.net`) || Host(`mapping.exactlylabs.com`)"
        - "traefik.http.services.mapping-client-app.loadbalancer.server.port=80"
        - "traefik.http.routers.mapping-client-app.entrypoints=web,websecure"
        - "traefik.http.routers.mapping-client-app.tls.certresolver=myresolver"

networks:
  traefik_public:
    external: true


