version: "3.8"

services:
  mlab-ingestor:
    image: registry.radartoolkit.com/mlab-ingestor:latest
    networks:
      - host_network # To allow access to clickhousedb
    environment:
      - DB_PORT=9000
      - DB_NAME=mlab-mapping
      - DB_USER=mapping
      - DB_HOST=localhost
      - S3_ACCESS_KEY=004049506844ea70000000001
      - S3_ENDPOINT=s3.us-west-004.backblazeb2.com
      - S3_REGION=us-west-004
      - FILES_BUCKET_NAME=radar-mlab-files
    secrets:
      - source: CLICKHOUSE_PASSWORD
        target: DB_PASSWORD
      - source: B2_SECRET_KEY
        target: S3_SECRET_KEY

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == tailscale
          - node.labels.service == clickhouse

networks:
  host_network:
    external:
      name: "host"


secrets:
  CLICKHOUSE_PASSWORD:
    external: true
  B2_SECRET_KEY:
    external: true
