version: 2.1

commands:
  install_python_deps:
    steps:
      - run: |
        sudo apt update && \
        sudo apt install -y \
        curl \
        python3 \
        python3-pip \
        git \
        tcpdump \
        netcat \
        iproute2 \
        arping
      - run: ./scripts/test_setup.sh

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: tianon/qemu:7.2-bullseye
    steps:
      - checkout
      - run: qemu-system-aarch64 --version




workflows:
  main_flow:
    jobs:
      - test:
          filters:
            branches:
              only: "/.*/"
