version: 2.1

commands:
  install_qemu:
    steps:
      - run: apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
      - run: apt-get install -y libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev
      - run: curl -o qemu_source.tar.xz https://download.qemu.org/qemu-7.2.2.tar.xz
      - run: tar -xvJf qemu_source.tar.xz
      - run: cd qemu-7.2.2 && ./configure
      - run: cd qemu-7.2.2 && make
      - run: cd qemu-7.2.2 && make install



jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18.2
    steps:
      - checkout
      - install_qemu




workflows:
  main_flow:
    jobs:
      - test:
          filters:
            branches:
              only: "/.*/"
