version: 2.1

commands:
  install_qemu:
    steps:
      - run: curl -o qemu_source.tar.xz https://download.qemu.org/qemu-7.2.2.tar.xz
      - run: tar -xvJf qemu_source.tar.xz
      - run: cd qemu-7.2.2 && ./configure
      - run: cd qemu-7.2.2 && make
      - run: cd qemu-7.2.2 && make install


jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/go.1.18.2
    steps:
      - checkout
      - install_qemu




workflows:
  main_flow:
    jobs:
      - test:
          filters:
            branches:
              only: "/.*/"
