version: 2.1

commands:

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: tianon/qemu:7.2-bullseye
    steps:
      - checkout
      - run: qemu-system-aarch64 --version




workflows:
  main_flow:
    jobs:
      - test:
          filters:
            branches:
              only: "/.*/"
