version: 2.1

commands:
  install_qemu:
    steps:
      - curl -o qemu_source.tar.xz https://download.qemu.org/qemu-7.2.2.tar.xz
      - tar -xvJf qemu_source.tar.xz
      - cd qemu-7.2.2
      - ./configure
      - make


jobs:
  test:
    working_directory: ~/repo
    docker:
      image: cimg/go.1.18.2
    steps:
      - checkout
      - install_qemu




workflows:
  main_flow:
    jobs:
      - test
