version: 2.1

commands:
  install_python_deps:
    steps:
      - run: |
          sudo apt update && \
          sudo apt install -y \
          curl \
          python3 \
          python3-pip \
          git \
          tcpdump \
          netcat \
          iproute2 \
          arping
      - run: ./scripts/test_setup.sh

  configure_image:
    steps:
      - run: sudo ./scripts/create_master_image.sh $POD_OS_ACCOUNT_TOKEN
      - run: echo $POD_OS_CONFIG_FILE | base64 -d > ./config.conf
      - run: ssh-keygen -q -t rsa -N '' -f ./tests/keys/id_rsa <<<y > /dev/null 2>&1
      - run: sudo ./scripts/dev_img.sh -c ./config.conf ./dist/radar.img ./tests/keys/id_rsa.pub

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: tianon/qemu:7.2-bullseye
    steps:
      - checkout
      - install_python_deps
      - configure_image
      - run: avocado run tests


workflows:
  main_flow:
    jobs:
      - test:
          filters:
            branches:
              only: "/.*/"
