// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClientsController from "./clients_controller.js"
application.register("clients", ClientsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import PasswordController from "./password_controller.js"
application.register("password", PasswordController)

import DrawerController from "./drawer_controller.js"
application.register("drawer", DrawerController)

import LocaltimeController from "./localtime_controller.js"
application.register("localtime", LocaltimeController)

import TimezoneController from "./timezone_controller.js"
application.register("timezone", TimezoneController)
