package update

import (
	"crypto"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/exactlylabs/radar/pods_agent/config"
	"google.golang.org/protobuf/proto"
)

var (
	ErrInvalidCertificate  error = errors.New("certificate is not valid")
	ErrCertificateRevoked  error = errors.New("certificate revoked")
	ErrInvalidSignature    error = errors.New("signature is not valid")
	ErrCRLNotFound         error = errors.New("crl not found")
	ErrCRLExpired          error = errors.New("CRL expired")
	ErrCRLInvalidSignature error = errors.New("CRL not generated by CA")
	ErrEmptyFile           error = errors.New("update file is empty")
	ErrVersionMismatch     error = errors.New("version mismatch")
)

func IsValidationError(err error) bool {
	return errors.Is(err, ErrInvalidCertificate) ||
		errors.Is(err, ErrCertificateRevoked) ||
		errors.Is(err, ErrInvalidSignature) ||
		errors.Is(err, ErrCRLNotFound) ||
		errors.Is(err, ErrCRLExpired) ||
		errors.Is(err, ErrCRLInvalidSignature)
}

// ParseUpdateFile will read from the reader and then validate the contents of it,
// ensuring that the file is a valid binary to update
func ParseUpdateFile(r io.Reader) ([]byte, error) {
	sb, err := readFile(r)
	if err != nil {
		return nil, err
	}
	rootCert, err := parseCertificate(rootCAFile)
	if err != nil {
		return nil, err
	}
	// Validating the Provider Certificate
	cert, err := parseCertificate(sb.GetCertificate())
	if err != nil {
		return nil, err
	}
	// Check if it's signed by our trusted CA
	if err := verifyCertificate(cert, rootCert); err != nil {
		return nil, ErrInvalidCertificate
	}

	if err := verifyCertIsRevoked(cert, rootCert); IsValidationError(err) {
		return nil, err
	} else if err != nil {
		return nil, ErrCertificateRevoked
	}

	// Validate the binary was not tampered
	if err := verifySignature(cert, sb.GetBinary(), sb.GetSignature()); err != nil {
		return nil, ErrInvalidSignature
	}

	return sb.GetBinary(), nil
}

func readFile(r io.Reader) (*SignedBinary, error) {
	data, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("update.ParseUpdateFile error reading: %w", err)
	}
	if len(data) == 0 {
		return nil, ErrEmptyFile
	}
	sb := &SignedBinary{}
	if err := proto.Unmarshal(data, sb); err != nil {
		return nil, fmt.Errorf("update.ParseUpdateFile error unmarshalling: %w", err)
	}
	return sb, nil
}

func parseCertificate(data []byte) (*x509.Certificate, error) {
	block, _ := pem.Decode(data)
	if block == nil {
		return nil, fmt.Errorf("update.parseCertificate invalid PEM format")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("update.parseCertificate error parsing: %w", err)
	}
	return cert, nil
}

func verifyCertificate(binCert, rootCert *x509.Certificate) error {
	if err := binCert.CheckSignatureFrom(rootCert); err != nil {
		return fmt.Errorf("update.verifyCertificate error: %w", err)
	}
	return nil
}

func verifyCertIsRevoked(binCert, rootCert *x509.Certificate) error {
	crl, err := loadCRL()
	if err != nil {
		return err
	}
	if err := rootCert.CheckCRLSignature(crl); err != nil {
		return ErrCRLInvalidSignature
	}
	if crl.HasExpired(time.Now()) {
		return ErrCRLExpired
	}
	for _, revoked := range crl.TBSCertList.RevokedCertificates {
		if revoked.SerialNumber != nil && revoked.SerialNumber.Cmp(binCert.SerialNumber) == 0 {
			return ErrCertificateRevoked
		}
	}
	return nil
}

func loadCRL() (*pkix.CertificateList, error) {
	crlUrl := config.LoadConfig().CRLUrl
	u, err := url.Parse(crlUrl)
	if err != nil {
		return nil, ErrCRLNotFound
	}
	var crlBytes []byte
	if u.Scheme == "https" || u.Scheme == "http" {
		res, err := http.Get(crlUrl)
		if err != nil {
			return nil, fmt.Errorf("update.loadCRL Get: %w", err)
		}
		defer res.Body.Close()
		crlBytes, err = ioutil.ReadAll(res.Body)
	} else if u.Scheme == "file" {
		f, err := os.Open(u.Host + u.Path)
		if err != nil {
			return nil, fmt.Errorf("update.loadCRL Open: %w", err)
		}
		defer f.Close()
		crlBytes, err = ioutil.ReadAll(f)
	} else {
		return nil, fmt.Errorf("update.loadCRL error: invalid CRLUrl configuration")
	}
	if err != nil {
		return nil, fmt.Errorf("update.loadCRL ReadAll: %w", err)
	}
	crlPem, _ := pem.Decode(crlBytes)
	crl, err := x509.ParseCRL(crlPem.Bytes)
	if err != nil {
		return nil, fmt.Errorf("update.loadCRL ParseCRL: %w", err)
	}
	return crl, nil
}

func verifySignature(binCert *x509.Certificate, binary []byte, signature []byte) error {
	hasher := sha256.New()
	hasher.Write(binary)
	binHash := hasher.Sum(nil)

	pbk := binCert.PublicKey.(*rsa.PublicKey)
	err := rsa.VerifyPKCS1v15(pbk, crypto.SHA256, binHash, signature)
	if err != nil {
		return fmt.Errorf("update.verifySignature error: %w", err)
	}
	return nil
}

func ParseSignedBinary(path string) (*SignedBinary, error) {
	s := &SignedBinary{}
	data, err := ioutil.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if err := proto.Unmarshal(data, s); err != nil {
		return nil, err
	}
	return s, nil
}

func validateBinaryVersion(binPath, expectedVersion string) error {
	out, err := exec.Command(binPath, "-v").Output()
	if err != nil {
		return fmt.Errorf("update.checkBinaryVersion Command: %w", err)
	}
	if !strings.Contains(string(out), expectedVersion) {
		return ErrVersionMismatch
	}
	return nil
}
