#!/usr/bin/env sh

set -e

CLIENT_ID=$(/app/radar-agent -vv | jq -r ".client_id")

echo "Pod Agent Docker Entrypoint. Client ID: $CLIENT_ID"

if [ -z "$CLIENT_ID" ]; then
  echo "No Client ID found for this agent. Registering it before executing the command."

  if [ ! -z "$RADAR_NETWORK_NAME" ]; then
    export RADAR_CREATE_NETWORK=true
  fi

  /app/radar-agent register

fi

exec "${@}"
