#!/usr/bin/env sh

set -e

CLIENT_ID=$(/app/radar-agent -vv | jq -r ".client_id")

echo "Pod Agent Docker Entrypoint. Client ID: $CLIENT_ID"

if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" = "null" ]; then
  echo "No Client ID found for this agent. Registering it before executing the command."

  if [ ! -z "$RADAR_NETWORK_NAME" ]; then
    export RADAR_CREATE_NETWORK=true
  fi
  export RADAR_REGISTER_LABEL=${RADAR_REGISTER_LABEL:-${FLOTO_DEVICE_UUID}}
  /app/radar-agent register

fi

set +e

# Be sure to send the SIGTERM signal to child process (agent)
_term() {
  echo "Caught SIGTERM signal!"
  kill -TERM $child 2>/dev/null
}
trap _term SIGTERM

while true
do
  # Start the agent in a child process, and restart it in case it exits with a non-zero code
  /app/radar-agent agent &
  child=$!
  wait "$child"
  res=$?
  echo "Exit code: $res"
  if [ $res -eq 0 ]; then
    break
  fi
  echo "Command failed. Retrying in 2 seconds."
  sleep 2
done
