// REGULAR STRINGIFIED COLORS
export const WHITE = 'white';
export const BLACK = 'black';

// SPECIFIC COLORS FROM DESIGN
export const DEFAULT_HEADER_BACKGROUND_COLOR = '#110e4c';
export const DEFAULT_FOOTER_BACKGROUND_COLOR = WHITE;
export const DEFAULT_TABS_BACKGROUND_COLOR = WHITE;
export const DEFAULT_BLUE_BUTTON_BACKGROUND_COLOR = '#4b7be5';
export const DEFAULT_BUTTON_BOX_SHADOW_RGBA = 'rgba(75, 123, 229, 0.5)';
export const DEFAULT_MAIN_SECTION_BACKGROUND_COLOR = '#f8f7ff';
export const DEFAULT_FOOTER_FONT_COLOR = '#6d6a94';
export const DEFAULT_UNSELECTED_TAB_COLOR = '#6d6a94';
export const DEFAULT_SELECTED_TAB_COLOR = '#4b7be5';
