receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 60s
  filter/host_metrics:
    metrics:
      include:
        match_type: regexp
        metric_names: ["system\\..*"]
  filter/service_metrics:
    metrics:
      exclude:
        match_type: regexp
        metric_names: ["system\\..*"]

exporters:
  prometheus/services:
    endpoint: "0.0.0.0:9464"
    send_timestamps: true
    namespace: "services"
  prometheus/host:
    endpoint: "0.0.0.0:9465"
    send_timestamps: true
    namespace: "host"
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    metrics/services:
      receivers: [otlp]
      processors: [filter/service_metrics, batch]
      exporters: [prometheus/services]
    metrics/host:
      receivers: [otlp]
      processors: [filter/host_metrics, batch]
      exporters: [prometheus/host]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
