# api:
#   enabled: false
#   address: 0.0.0.0:8686

sources:
  docker_logs:
    type: docker_logs
    exclude_containers:
      - "vector"
      - "swarmpit"
      - "traefik"

  traefik_logs:
    type: "docker_logs"
    include_containers:
      - "traefik"

transforms:
  traefik_logs_decode:
    type: remap
    inputs: ["traefik_logs"]
    source: |-
      .access_data = parse_json!(.message)


sinks:
  docker_logs_sink:
    type: "loki"
    inputs: ["docker_logs"]
    endpoint: "http://loki:3100"
    encoding:
      codec: "json"
    labels:
      host: {{ "\"{{ host }}\"" }}
      source: "docker"
      job: "docker-logs"
    healthcheck:
      enabled: false

  traefik_access_sink:
    type: "loki"
    inputs: ["traefik_logs_decode"]
    endpoint: "http://loki:3100"
    encoding:
      codec: "json"
    labels:
      host: {{ "\"{{ host }}\"" }}
      source: "traefik"
      job: "traefik-access"
    healthcheck:
      enabled: false

  # debug:
  #   type: "console"
  #   inputs: ["traefik_logs"]
  #   encoding:
  #     codec: "text"
