version: "3.9"
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    shm_size: 1g
    ports:
    - 54321:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=mlab-mapping

