version: "3.8"

services:
  speedtest-client:
    image: registry.staging.radartoolkit.com/speedtest-client:latest
    networks:
      - traefik_public
    environment:
      - NODE_ENV=staging
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.speedtest-client-app.rule=Host(`speed.staging.radartoolkit.com`)"
        - "traefik.http.services.speedtest-client-app.loadbalancer.server.port=9999"
        - "traefik.http.routers.speedtest-client-app.entrypoints=web,websecure"
        - "traefik.http.routers.speedtest-client-app.tls.certresolver=myresolver"

networks:
  traefik_public:
    external: true


