# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws_mobile_messages.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ws_mobile_messages.proto", :syntax => :proto3) do
    add_message "ws_mobile_messages_pb.ScannedAP" do
      optional :bssid, :string, 1
      optional :ssid, :string, 2
      optional :capabilities, :string, 3
      optional :level, :int32, 4
      optional :frequency, :int32, 5
      optional :center_freq0, :int32, 6
      optional :center_freq1, :int32, 7
      optional :is80211mc_responder, :bool, 8
      optional :channel_width, :int32, 9
      optional :is_passpoint_network, :bool, 10
      optional :information_elements, :bytes, 11
      optional :wifi_standard, :int32, 12
      optional :timestamp, :message, 13, "google.protobuf.Timestamp"
    end
    add_message "ws_mobile_messages_pb.ScanResult" do
      repeated :scanned_aps, :message, 1, "ws_mobile_messages_pb.ScannedAP"
      optional :latitude, :float, 2
      optional :longitude, :float, 3
    end
    add_message "ws_mobile_messages_pb.WSMessage" do
      optional :event, :enum, 1, "ws_mobile_messages_pb.Events"
      oneof :message do
        optional :scan_result, :message, 2, "ws_mobile_messages_pb.ScanResult"
        optional :timestamp, :message, 3, "google.protobuf.Timestamp"
        optional :json, :string, 4
      end
    end
    add_enum "ws_mobile_messages_pb.Events" do
      value :SCAN_RESULT, 0
      value :SCAN_START, 1
      value :SCAN_STOP, 2
      value :WELCOME, 3
      value :PING, 4
      value :Other, 99
    end
  end
end

module WsMobileMessagesPb
  ScannedAP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ws_mobile_messages_pb.ScannedAP").msgclass
  ScanResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ws_mobile_messages_pb.ScanResult").msgclass
  WSMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ws_mobile_messages_pb.WSMessage").msgclass
  Events = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ws_mobile_messages_pb.Events").enummodule
end
