default_platform(:ios)
platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :sign_dev do
    build_app(
      skip_build_archive: true,
      scheme: "dev",
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: "MQYTP6VS48",    
      export_method: "ad-hoc",
  )
  end
  
  lane :sign_staging do
    # Use the compiled .xarchive and just sign it to transform into an .ipa
    build_app(
        skip_build_archive: true,
        scheme: "staging",
        archive_path: "../build/ios/archive/Runner.xcarchive",
        export_team_id: "MQYTP6VS48",
    )
  end

  lane :sign_prod do
    # Use the compiled .xarchive and just sign it to transform into an .ipa
    build_app(
        skip_build_archive: true,
        scheme: "prod",
        archive_path: "../build/ios/archive/Runner.xcarchive",
        export_team_id: "5SC4GE8QS7",
    )
  end

  lane :release_staging do
    # Upload to TestFlight
    app_store_connect_api_key
    changelog_from_git_commits(
      merge_commit_filtering: 'exclude_merges'
    )
    upload_to_testflight(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["QA"],
    )
  end

  lane :release_prod do
    app_store_connect_api_key
    changelog_from_git_commits(
      merge_commit_filtering: 'exclude_merges'
    )
    upload_to_app_store
  end
end
