# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
# app_store_connect_api_key
platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :dev do
    build_app(
      skip_build_archive: true,
      scheme: "dev",
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: "MQYTP6VS48",      
  )
  end
  
  lane :sign_staging do
    # How to increment build number with fastlane:
    # increment_build_number(
    #   build_number: app_store_build_number(
    #     initial_build_number: 1,
    #     version: get_version_number(xcodeproj: "HelloCircle.xcodeproj"),
    #     live: false
    #   ) + 1,
    # )
    # app_identifier("com.exactlylabs.radar.staging")
    # Flutter requires us to build using it first
    build_app(
        skip_build_archive: true,
        scheme: "staging",
        archive_path: "../build/ios/archive/Runner.xcarchive",
        export_team_id: "MQYTP6VS48",
        # export_options: {}
    )
  end

  lane release_staging: do
    # Upload to TestFlight
    pilot(
      distribute_external: true,
      notify_external_testers: true,
      groups: ["QA"],
      changelog: "Test Changelog"
    )
  end

  lane :release_dev do
    # Flutter requires us to build using it first
    build_app(
        skip_build_archive: true,
        archive_path: "../build/ios/archive/Runner.xcarchive",
    )

  end
end
