# Took from https://github.com/AlexeySetevoi/ansible-clickhouse/blob/master/defaults/main.yml
---
# defaults file for clickhouse

clickhouse_version: 'latest'
clickhouse_service_ensure: 'started'
clickhouse_service_enable: true

#Type of installation (package,source)
clickhouse_setup: 'package'

clickhouse_profiles_custom: {}

clickhouse_listen_host_default:
  - "::1"
  - "127.0.0.1"

clickhouse_listen_host_custom: []

clickhouse_listen_host: "{{ clickhouse_listen_host_default + clickhouse_listen_host_custom }}"

clickhouse_https_port: 8443
clickhouse_tcp_secure_port: 9440

clickhouse_ssl_server:
  certificate_file: "/etc/clickhouse-server/server.crt"
  private_key_file: "/etc/clickhouse-server/server.key"
  verification_mode: "none"
  load_default_ca_file: "true"
  cache_sessions: "true"
  disable_protocols: "sslv2,sslv3"
  prefer_server_ciphers: "true"

clickhouse_ssl_client:
  load_default_ca_file: "true"
  cache_sessions: "true"
  disable_protocols: "sslv2,sslv3"
  prefer_server_ciphers: "true"
  invalid_certificate_handler_name: "RejectCertificateHandler"

clickhouse_path_base: "/var/lib"
clickhouse_path_user_files: "{{ clickhouse_path_base }}/clickhouse/user_files/"

clickhouse_ready_delay: 5

#Full form { name:'<username>', password: '<plainpassword>', password_sha256_hex: '<sha256password>',
#   networks:"<{} with nets>", profile:'<profile>', quota:'<quota>', dbs: '{} with dbs', comment: '<some comment>'}
#Req: name, password or password_256_hex
clickhouse_users_custom: {}

clickhouse_dbs_default: []
clickhouse_dbs_custom: []

clickhouse_dbs: "{{ clickhouse_dbs_default + clickhouse_dbs_custom }}"

clickhouse_config:
  max_connections: 2048
  keep_alive_timeout: 3
  max_concurrent_queries: 100
  max_session_timeout: 3600
  default_session_timeout: 60
