version: '3.8'

services:
  vector-agent:
    image: timberio/vector:latest-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    deploy:
      mode: global
    hostname: "{{.Node.Hostname}}"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAU6GDYLAR2HPLNOIB
      - AWS_SECRET_ACCESS_KEY=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
    configs:
      - source: vector_config-v32
        target: /etc/vector/vector.yaml


configs:
  # To update config files, we must rename the config key name, and update the service to source from this new name.
  # see for more: https://docs.docker.com/engine/swarm/configs/#example-rotate-a-config
  vector_config-v32:
    template_driver: golang
    file: ./configs/vector.yaml


networks:
  public:
    driver: overlay
    attachable: true

