// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Exactly Labs",
            "url": "https://exactlylabs.com",
            "email": "devops@exactlylabs.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/asns": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "text to filter for",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/paginator.PaginatedResponse-storages_ASNOrg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        },
        "/geojson": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "name": "asn_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Weeks of the Year.",
                        "name": "week",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        },
        "/geospaces": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "text to filter for",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/paginator.PaginatedResponse-storages_DetailedGeospace"
                        }
                    }
                }
            }
        },
        "/geospaces/{id}/asns": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geospace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "text to filter for",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/paginator.PaginatedResponse-storages_ASNOrg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        },
        "/geospaces/{id}/overview": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geospace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Additionally filter by an ASN",
                        "name": "asn_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Weeks of the Year.",
                        "name": "week",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storages.GeospaceSummaryResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        },
        "/namespaces/{namespace}/geospaces": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace to list",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "text to filter for",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.ListNamespaceGeospacesResult"
                        }
                    }
                }
            }
        },
        "/namespaces/{namespace}/geospaces/{geoid}/asns": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Geospace's namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "GEOID that belongs to the namespace",
                        "name": "geoid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "text to filter for",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/paginator.PaginatedResponse-storages_ASNOrg"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        },
        "/namespaces/{namespace}/tiles/{z}/{x}/{y}": {
            "get": {
                "produces": [
                    "application/vnd.mapbox-vector-tile"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace to return the tiles",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "zoom level",
                        "name": "z",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "tile x position",
                        "name": "x",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "tile y position",
                        "name": "y",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "asn_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Weeks of the Year.",
                        "name": "week",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "encoded vector tile",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apierrors.RequestError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apierrors.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apierrors.RequestError": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/apierrors.APIError"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "paginator.PaginatedResponse-storages_ASNOrg": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/paginator.PaginationLinks"
                },
                "count": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storages.ASNOrg"
                    }
                }
            }
        },
        "paginator.PaginatedResponse-storages_DetailedGeospace": {
            "type": "object",
            "properties": {
                "_links": {
                    "$ref": "#/definitions/paginator.PaginationLinks"
                },
                "count": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storages.DetailedGeospace"
                    }
                }
            }
        },
        "paginator.PaginationLinks": {
            "type": "object",
            "properties": {
                "next": {
                    "type": "string"
                },
                "previous": {
                    "type": "string"
                }
            }
        },
        "routes.ListNamespaceGeospacesResult": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storages.DetailedGeospace"
                    }
                }
            }
        },
        "storages.ASNOrg": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "organization": {
                    "type": "string"
                }
            }
        },
        "storages.DetailedGeospace": {
            "type": "object",
            "properties": {
                "centroid": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "geo_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "parent": {
                    "$ref": "#/definitions/storages.Geospace"
                }
            }
        },
        "storages.Geospace": {
            "type": "object",
            "properties": {
                "centroid": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "geo_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                }
            }
        },
        "storages.GeospaceSummaryResult": {
            "type": "object",
            "properties": {
                "asn": {
                    "$ref": "#/definitions/storages.ASNOrg"
                },
                "download_median": {
                    "type": "number"
                },
                "download_scores": {
                    "$ref": "#/definitions/storages.MeasurementScore"
                },
                "geospace": {
                    "$ref": "#/definitions/storages.DetailedGeospace"
                },
                "latency_median": {
                    "type": "number"
                },
                "upload_median": {
                    "type": "number"
                },
                "upload_scores": {
                    "$ref": "#/definitions/storages.MeasurementScore"
                }
            }
        },
        "storages.MeasurementScore": {
            "type": "object",
            "properties": {
                "bad": {
                    "type": "number"
                },
                "good": {
                    "type": "number"
                },
                "medium": {
                    "type": "number"
                },
                "total_samples": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "api.mapping.exactlylabs.com",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Broadband Mapping API",
	Description:      "This api provides a summary of broadband measurements for the US based on geolocations (geospaces)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
