basePath: /api/v1
consumes:
- application/json
definitions:
  apierrors.APIError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  apierrors.RequestError:
    properties:
      errors:
        additionalProperties:
          items:
            $ref: '#/definitions/apierrors.APIError'
          type: array
        type: object
      message:
        type: string
      status:
        type: string
    type: object
  paginator.PaginatedResponse-storages_ASNOrg:
    properties:
      _links:
        $ref: '#/definitions/paginator.PaginationLinks'
      count:
        type: integer
      results:
        items:
          $ref: '#/definitions/storages.ASNOrg'
        type: array
    type: object
  paginator.PaginatedResponse-storages_DetailedGeospace:
    properties:
      _links:
        $ref: '#/definitions/paginator.PaginationLinks'
      count:
        type: integer
      results:
        items:
          $ref: '#/definitions/storages.DetailedGeospace'
        type: array
    type: object
  paginator.PaginationLinks:
    properties:
      next:
        type: string
      previous:
        type: string
    type: object
  routes.ListNamespaceGeospacesResult:
    properties:
      results:
        items:
          $ref: '#/definitions/storages.DetailedGeospace'
        type: array
    type: object
  storages.ASNOrg:
    properties:
      id:
        type: string
      organization:
        type: string
    type: object
  storages.DetailedGeospace:
    properties:
      centroid:
        items:
          type: number
        type: array
      geo_id:
        type: string
      id:
        type: string
      name:
        type: string
      namespace:
        type: string
      parent:
        $ref: '#/definitions/storages.Geospace'
    type: object
  storages.Geospace:
    properties:
      centroid:
        items:
          type: number
        type: array
      geo_id:
        type: string
      id:
        type: string
      name:
        type: string
      namespace:
        type: string
      parent_id:
        type: string
    type: object
  storages.GeospaceSummaryResult:
    properties:
      asn:
        $ref: '#/definitions/storages.ASNOrg'
      download_median:
        type: number
      download_scores:
        $ref: '#/definitions/storages.MeasurementScore'
      geospace:
        $ref: '#/definitions/storages.DetailedGeospace'
      latency_median:
        type: number
      upload_median:
        type: number
      upload_scores:
        $ref: '#/definitions/storages.MeasurementScore'
    type: object
  storages.MeasurementScore:
    properties:
      bad:
        type: number
      good:
        type: number
      medium:
        type: number
      total_samples:
        type: integer
    type: object
host: api.mapping.exactlylabs.com
info:
  contact:
    email: devops@exactlylabs.com
    name: Exactly Labs
    url: https://exactlylabs.com
  description: This api provides a summary of broadband measurements for the US based
    on geolocations (geospaces)
  title: Broadband Mapping API
  version: 0.1.0
paths:
  /asns:
    get:
      parameters:
      - description: text to filter for
        in: query
        name: query
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/paginator.PaginatedResponse-storages_ASNOrg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
  /geojson:
    get:
      parameters:
      - in: query
        name: asn_id
        type: string
      - in: query
        name: month
        type: integer
      - in: query
        name: namespace
        type: string
      - in: query
        name: quarter
        type: integer
      - in: query
        name: semester
        type: integer
      - description: Weeks of the Year.
        in: query
        name: week
        type: integer
      - in: query
        name: year
        type: integer
      responses:
        "200":
          description: OK
          schema: {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
  /geospaces:
    get:
      parameters:
      - description: text to filter for
        in: query
        name: query
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/paginator.PaginatedResponse-storages_DetailedGeospace'
  /geospaces/{id}/asns:
    get:
      parameters:
      - description: Geospace ID
        in: path
        name: id
        required: true
        type: string
      - description: text to filter for
        in: query
        name: query
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/paginator.PaginatedResponse-storages_ASNOrg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
  /geospaces/{id}/overview:
    get:
      parameters:
      - description: Geospace ID
        in: path
        name: id
        required: true
        type: string
      - description: Additionally filter by an ASN
        in: query
        name: asn_id
        type: string
      - in: query
        name: month
        type: integer
      - in: query
        name: quarter
        type: integer
      - in: query
        name: semester
        type: integer
      - description: Weeks of the Year.
        in: query
        name: week
        type: integer
      - in: query
        name: year
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storages.GeospaceSummaryResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
  /namespaces/{namespace}/geospaces:
    get:
      parameters:
      - description: namespace to list
        in: path
        name: namespace
        required: true
        type: string
      - description: text to filter for
        in: query
        name: query
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.ListNamespaceGeospacesResult'
  /namespaces/{namespace}/geospaces/{geoid}/asns:
    get:
      parameters:
      - description: Geospace's namespace
        in: path
        name: namespace
        required: true
        type: string
      - description: GEOID that belongs to the namespace
        in: path
        name: geoid
        required: true
        type: string
      - description: text to filter for
        in: query
        name: query
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/paginator.PaginatedResponse-storages_ASNOrg'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
  /namespaces/{namespace}/tiles/{z}/{x}/{y}:
    get:
      parameters:
      - description: Namespace to return the tiles
        in: path
        name: namespace
        required: true
        type: string
      - description: zoom level
        in: path
        name: z
        required: true
        type: integer
      - description: tile x position
        in: path
        name: x
        required: true
        type: integer
      - description: tile y position
        in: path
        name: "y"
        required: true
        type: integer
      - in: query
        name: asn_id
        type: string
      - in: query
        name: month
        type: integer
      - in: query
        name: quarter
        type: integer
      - in: query
        name: semester
        type: integer
      - description: Weeks of the Year.
        in: query
        name: week
        type: integer
      - in: query
        name: year
        type: integer
      produces:
      - application/vnd.mapbox-vector-tile
      responses:
        "200":
          description: encoded vector tile
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.RequestError'
produces:
- application/json
swagger: "2.0"
