version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create_version:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run: VERSION=$CIRCLE_TAG ./ci_scripts/create_version.sh

  build:
    working_directory: ~/repo
    docker:
      # Available Images: https://circleci.com/developer/images/image/cimg/go
      - image: cimg/go:1.18.2
    parameters:
      os:
        default: "linux"
        type: string
      arch:
        default: "amd64"
        type: string
      binName:
        default: "radar_agent"
        type: string
    
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: VERSION=$CIRCLE_TAG OS=<<parameters.os>> ARCH=<<parameters.arch>> BIN_NAME=<<parameters.binName>> ./ci_scripts/build.sh
      - persist_to_workspace:
          root: agent/dist
          paths:
            - <<parameters.binName>>
            - <<parameters.binName>>_signed

  upload:
    working_directory: ~/repo
    docker:
      # Available Images: https://circleci.com/developer/images/image/cimg/go
      - image: cimg/base:2022.05
    parameters:
      os:
        default: "linux"
        type: string
      arch:
        default: "amd64"
        type: string
      binName:
        default: "radar_agent"
        type: string
    
    steps:      
      - checkout
      - attach_workspace:
          at: /tmp/dist
      - run: VERSION=$CIRCLE_TAG BIN_NAME=<<parameters.binName>> DIST_NAME=<<parameters.os>>-<<parameters.arch>> ./ci_scripts/upload.sh
      

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:  
  build_linux_amd64:
    jobs:
      - create_version:
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
      - build:
          requires: [ create_version ]
          os: "linux"
          arch: "amd64"
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"

      - upload:
          requires: [ build ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: "linux"
          arch: "amd64"
  
  build_linux_arm64:
    jobs:
      - create_version:
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"

      - build:
          requires: [ create_version ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: "linux"
          arch: "arm64"
      - upload:
          requires: [ build ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: "linux"
          arch: "arm64"
      
  build_darwin_amd64:
    jobs:
      - create_version:
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"

      - build:
          requires: [ create_version ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: darwin
          arch: "amd64"
      - upload:
          requires: [ build ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: darwin
          arch: "amd64"
      
  build_windows_amd64:
    jobs:
      - create_version:
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"

      - build:
          requires: [ create_version ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: windows
          arch: "amd64"
          binName: "radar_agent.exe"
      - upload:
          requires: [ build ]
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          os: windows
          arch: "amd64"
          binName: "radar_agent.exe"
