version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create_version:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run: VERSION=$CIRCLE_TAG ./ci_scripts/create_version.sh

  build_and_upload:
    working_directory: ~/repo
    docker:
      # Available Images: https://circleci.com/developer/images/image/cimg/go
      - image: cimg/go:1.18.2
    parameters:
      version:
        type: string
      os:
        default: "linux"
        type: string
      arch:
        default: "amd64"
        type: string
      binName:
        default: "radar_agent"
        type: string
    
    steps:
      - checkout
      - run: VERSION=<<parameters.version>> OS=<<parameters.os>> ARCH=<<parameters.arch>> BIN_NAME=<<parameters.binName>> ./ci_scripts/build.sh
      - run: VERSION=<<parameters.version>> BIN_NAME=<<parameters.binName>> DIST_NAME=<<parameters.os>>-<<parameters.arch>> ./ci_scripts/upload.sh


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:  
  build:
    jobs:
      - create_version:
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
            
      - build_and_upload:
          requires: [ create_version ]
          version: $CIRCLE_TAG
          filters:
            tags:
              only: /^(?:\d+\.){2}\d+$/
            branches:
              ignore: "/.*/"
          matrix:
            parameters:
              os: ["linux", "darwin", "windows"]
              arch: ["amd64", "arm64"]
            exclude:
              - os: "windows"
                arch: "arm64"

          