---
- name: Get Host's Architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Set Architecture
  set_fact:
    deb_architecture: "{{ deb_architecture.stdout }}"

- name: Set Docker Key URL
  set_fact:
    key_url: https://download.docker.com/linux/ubuntu/gpg
    repository_url: https://download.docker.com/linux/ubuntu
  when: ansible_distribution == "Ubuntu"

- name: Set Docker Key URL
  set_fact:
    key_url: https://download.docker.com/linux/debian/gpg
    repository_url: https://download.docker.com/linux/debian
  when: ansible_distribution == "Debian"

- name: Install required system packages
  become: yes
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add Docker Repository
  become: yes
  block:
    - name: grab docker gpg key
      ansible.builtin.get_url:
        url: "{{ key_url }}"
        dest: /etc/apt/keyrings/docker.asc
    - name: add docker repository
      apt_repository:
        repo: deb [arch={{ deb_architecture }} signed-by=/etc/apt/keyrings/docker.asc] {{ repository_url }} {{ ansible_distribution_release }} stable
        state: present

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Start Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Module for Python
  become: yes
  apt:
    name:
      - python3-docker
    state: latest
    update_cache: yes
