# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("DB_MAX_POOL_SIZE") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" }%>
  username: <%= ENV.fetch("DB_USER") { "postgres" }%>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" }%>
  <% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"].sub(/^postgres/, "postgis") %>
  <% end %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "radar_development" } %>

test:
  <<: *default
  database: radar_test

staging:
  <<: *default
  database: radar
  username: radar
  password: <%= ENV['RADAR_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: radar_production
  username: radar
  password: <%= ENV['RADAR_DATABASE_PASSWORD'] %>
