---
- name: restart postgresql service
  become: yes
  systemd:
    name: "postgresql"
    state: restarted
    enabled: yes

- name: reload postgresql service
  become: yes
  systemd:
    name: "postgresql"
    state: reloaded
    enabled: yes

