// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccountsDrawerMenuController from "./accounts_drawer_menu_controller"
application.register("accounts-drawer-menu", AccountsDrawerMenuController)

import AddAccountController from "./add_account_controller"
application.register("add-account", AddAccountController)

import AddClientToLocationController from "./add_client_to_location_controller"
application.register("add-client-to-location", AddClientToLocationController)

import AddPodController from "./add_pod_controller"
application.register("add-pod", AddPodController)

import AddPodToNetworkController from "./add_pod_to_network_controller"
application.register("add-pod-to-network", AddPodToNetworkController)

import AddUserController from "./add_user_controller"
application.register("add-user", AddUserController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AlertHandlerController from "./alert_handler_controller"
application.register("alert-handler", AlertHandlerController)

import AppSearchController from "./app_search_controller"
application.register("app-search", AppSearchController)

import BannerController from "./banner_controller"
application.register("banner", BannerController)

import BarChartController from "./bar_chart_controller"
application.register("bar-chart", BarChartController)

import BulkReleaseGroupModalController from "./bulk_release_group_modal_controller"
application.register("bulk-release-group-modal", BulkReleaseGroupModalController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import CategoryTooltipController from "./category_tooltip_controller"
application.register("category-tooltip", CategoryTooltipController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ClaimPodsController from "./claim_pods_controller"
application.register("claim-pods", ClaimPodsController)

import ClientDataCapFormController from "./client_data_cap_form_controller"
application.register("client-data-cap-form", ClientDataCapFormController)

import ClientSchedulingFormController from "./client_scheduling_form_controller"
application.register("client-scheduling-form", ClientSchedulingFormController)

import CollapsibleRowController from "./collapsible_row_controller"
application.register("collapsible-row", CollapsibleRowController)

import CustomModalController from "./custom_modal_controller"
application.register("custom-modal", CustomModalController)

import DashboardTimeFilterController from "./dashboard_time_filter_controller"
application.register("dashboard-time-filter", DashboardTimeFilterController)

import DownloadsController from "./downloads_controller"
application.register("downloads", DownloadsController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import EditAccountController from "./edit_account_controller"
application.register("edit-account", EditAccountController)

import EditPasswordController from "./edit_password_controller"
application.register("edit-password", EditPasswordController)

import EditPodController from "./edit_pod_controller"
application.register("edit-pod", EditPodController)

import EditProfilePictureController from "./edit_profile_picture_controller"
application.register("edit-profile-picture", EditProfilePictureController)

import ErrorHandlerController from "./error_handler_controller"
application.register("error-handler", ErrorHandlerController)

import ExportsController from "./exports_controller"
application.register("exports", ExportsController)

import FeatureFlagsController from "./feature_flags_controller"
application.register("feature-flags", FeatureFlagsController)

import FetchController from "./fetch_controller"
application.register("fetch", FetchController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import LineChartController from "./line_chart_controller"
application.register("line-chart", LineChartController)

import LoadingFeedbackController from "./loading_feedback_controller"
application.register("loading-feedback", LoadingFeedbackController)

import LocaltimeController from "./localtime_controller"
application.register("localtime", LocaltimeController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import LocationFormController from "./location_form_controller"
application.register("location-form", LocationFormController)

import LocationsMapWidgetController from "./locations_map_widget_controller"
application.register("locations-map-widget", LocationsMapWidgetController)

import MapController from "./map_controller"
application.register("map", MapController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MoreOptionsButtonController from "./more_options_button_controller"
application.register("more-options-button", MoreOptionsButtonController)

import MultiLineChartController from "./multi_line_chart_controller"
application.register("multi-line-chart", MultiLineChartController)

import MultiPodSelectController from "./multi_pod_select_controller"
application.register("multi-pod-select", MultiPodSelectController)

import MultiRowTableController from "./multi_row_table_controller"
application.register("multi-row-table", MultiRowTableController)

import NotificationSettingsController from "./notification_settings_controller"
application.register("notification-settings", NotificationSettingsController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import OnboardController from "./onboard_controller"
application.register("onboard", OnboardController)

import OutagesChartController from "./outages_chart_controller"
application.register("outages-chart", OutagesChartController)

import OutagesModalController from "./outages_modal_controller"
application.register("outages-modal", OutagesModalController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import PasswordRevealController from "./password_reveal_controller"
application.register("password-reveal", PasswordRevealController)

import PodAccountAndNetworkController from "./pod_account_and_network_controller"
application.register("pod-account-and-network", PodAccountAndNetworkController)

import PublicPageController from "./public_page_controller"
application.register("public-page", PublicPageController)

import PublicPageModalController from "./public_page_modal_controller"
application.register("public-page-modal", PublicPageModalController)

import PublicPodTabsController from "./public_pod_tabs_controller"
application.register("public-pod-tabs", PublicPodTabsController)

import QaController from "./qa_controller"
application.register("qa", QaController)

import QrController from "./qr_controller"
application.register("qr", QrController)

import RegistrationController from "./registration_controller"
application.register("registration", RegistrationController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import SelectedPodsGridController from "./selected_pods_grid_controller"
application.register("selected-pods-grid", SelectedPodsGridController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SignInController from "./sign_in_controller"
application.register("sign-in", SignInController)

import SpeedFiltersController from "./speed_filters_controller"
application.register("speed-filters", SpeedFiltersController)

import StateTabsController from "./state_tabs_controller"
application.register("state-tabs", StateTabsController)

import SuperUserController from "./super_user_controller"
application.register("super-user", SuperUserController)

import SwitchAccountController from "./switch_account_controller"
application.register("switch-account", SwitchAccountController)

import TableController from "./table_controller"
application.register("table", TableController)

import TimezoneController from "./timezone_controller"
application.register("timezone", TimezoneController)

import UpdateGroupController from "./update_group_controller"
application.register("update-group", UpdateGroupController)

import WidgetsController from "./widgets_controller"
application.register("widgets", WidgetsController)
