// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import StagingClientsController from "./staging_clients_controller.js"
application.register("staging-clients", StagingClientsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import PasswordController from "./password_controller.js"
application.register("password", PasswordController)

import LocationController from "./location_controller.js"
application.register("location", LocationController)

import LocationFormController from "./location_form_controller.js"
application.register("location-form", LocationFormController)

import DrawerController from "./drawer_controller.js"
application.register("drawer", DrawerController)

import LocaltimeController from "./localtime_controller.js"
application.register("localtime", LocaltimeController)

import TimezoneController from "./timezone_controller.js"
application.register("timezone", TimezoneController)

import OnboardController from "./onboard_controller.js"
application.register("onboard", OnboardController)

import Select2Controller from "./select2_controller.js"
application.register("select2", Select2Controller)

import MapController from "./map_controller.js"
application.register("map", MapController);