// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller.js";
application.register("hello", HelloController);

import ModalController from "./modal_controller.js";
application.register("modal", ModalController);

import MenuController from "./menu_controller.js";
application.register("menu", MenuController);

import PasswordController from "./password_controller.js";
application.register("password", PasswordController);

import LocationController from "./location_controller.js";
application.register("location", LocationController);

import LocationFormController from "./location_form_controller.js";
application.register("location-form", LocationFormController);

import DrawerController from "./drawer_controller.js";
application.register("drawer", DrawerController);

import LocaltimeController from "./localtime_controller.js";
application.register("localtime", LocaltimeController);

import TimezoneController from "./timezone_controller.js";
application.register("timezone", TimezoneController);

import OnboardController from "./onboard_controller.js";
application.register("onboard", OnboardController);

import Select2Controller from "./select2_controller.js";
application.register("select2", Select2Controller);

import MapController from "./map_controller.js";
application.register("map", MapController);

import AddClientToLocation from "./add_client_to_location_controller.js";
application.register("add-client-to-location", AddClientToLocation);

import AddPodController from "./add_pod_controller.js";
application.register("add-pod", AddPodController);

import EditPodController from "./edit_pod_controller.js";
application.register("edit-pod", EditPodController);

import RegistrationController from "./registration_controller.js";
application.register("registration", RegistrationController);

import AddAccountController from "./add_account_controller.js";
application.register("add-account", AddAccountController);

import SwitchAccountController from "./switch_account_controller.js";
application.register("switch-account", SwitchAccountController);

import AddUserController from "./add_user_controller.js";
application.register("add-user", AddUserController);

import SignInController from "./sign_in_controller.js";
application.register("sign-in", SignInController);

import AccountsDrawerMenuController from "./accounts_drawer_menu_controller.js";
application.register("accounts-drawer-menu", AccountsDrawerMenuController);

import EditProfilePictureController from "./edit_profile_picture_controller.js";
application.register("edit-profile-picture", EditProfilePictureController);

import PasswordRevealController from "./password_reveal_controller.js";
application.register("password-reveal", PasswordRevealController);

import ClientDataCapFormController from "./client_data_cap_form_controller";
application.register("client-data-cap-form", ClientDataCapFormController);

import ClientSchedulingFormController from "./client_scheduling_form_controller";
application.register("client-scheduling-form", ClientSchedulingFormController);

import MultiRowTableController from "./multi_row_table_controller";
application.register("multi-row-table", MultiRowTableController);

import BulkReleaseGroupModal from "./bulk_release_group_modal_controller";
application.register("bulk-release-group-modal", BulkReleaseGroupModal);

import ExportsController from './exports_controller';
application.register("exports", ExportsController);

import PublicPageController from './public_page_controller';
application.register("public-page", PublicPageController);

import CategoriesController from './categories_controller';
application.register("categories", CategoriesController);

import SearchController from './search_controller';
application.register("search", SearchController);

import CategoryTooltipController from './category_tooltip_controller';
application.register("category-tooltip", CategoryTooltipController);

import FetchController from './fetch_controller';
application.register("fetch", FetchController);

import AlertController from './alert_controller';
application.register("alert", AlertController);

import SidebarController from './sidebar_controller';
application.register("sidebar", SidebarController);

import UpdateGroupController from './update_group_controller';
application.register("update-group", UpdateGroupController);

import AppSearchController from './app_search_controller';
application.register("app-search", AppSearchController);

import BannerController from './banner_controller';
application.register("banner", BannerController);

import SuperUserController from './super_user_controller';
application.register("super-user", SuperUserController);

import PaginationController from './pagination_controller';
application.register("pagination", PaginationController);

import MoreOptionsButtonController from './more_options_button_controller';
application.register("more-options-button", MoreOptionsButtonController);

import TableController from './table_controller';
application.register("table", TableController);

import FiltersController from './filters_controller';
application.register("filters", FiltersController);

import CustomModalController from './custom_modal_controller';
application.register("custom-modal", CustomModalController);

import EditAccountController from './edit_account_controller';
application.register("edit-account", EditAccountController);

import EditPasswordController from './edit_password_controller';
application.register("edit-password", EditPasswordController);

import FeatureFlagsController from './feature_flags_controller';
application.register("feature-flags", FeatureFlagsController);

import SpeedFiltersController from './speed_filters_controller';
application.register("speed-filters", SpeedFiltersController);

import LocationsMapWidget from './locations_map_widget_controller';
application.register("locations-map-widget", LocationsMapWidget);

import DownloadsController from './downloads_controller';
application.register("downloads", DownloadsController);

import AddPodToNetworkController from "./add_pod_to_network_controller";
application.register("add-pod-to-network", AddPodToNetworkController);

import PodIdInputController from "./pod_id_input_controller";
application.register("pod-id-input", PodIdInputController);

import PodIdStepController from "./pod_id_step_controller";
application.register("pod-id-step", PodIdStepController);

import PodAccountAndNetworkController from "./pod_account_and_network_controller";
application.register("pod-account-and-network", PodAccountAndNetworkController);

import LoadingFeedbackController from "./loading_feedback_controller";
application.register("loading-feedback", LoadingFeedbackController);

import QrController from "./qr_controller";
application.register("qr", QrController);

import MultiPodSelectController from "./multi_pod_select_controller";
application.register("multi-pod-select", MultiPodSelectController);

import SelectedPodsGridController from "./selected_pods_grid_controller";
application.register("selected-pods-grid", SelectedPodsGridController);

import StateTabs from "./state_tabs_controller";
application.register("state-tabs", StateTabs);

import QA from "./qa_controller";
application.register("qa", QA);

import PublicPageModalController from "./public_page_modal_controller";
application.register("public-page-modal", PublicPageModalController);

import NotificationsController from "./notifications_controller";
application.register("notifications", NotificationsController);

import ChartController from "./chart_controller";
application.register("chart", ChartController);

import LineChartController from "./line_chart_controller";
application.register("line-chart", LineChartController);

import MultiLineChartController from "./multi_line_chart_controller";
application.register("multi-line-chart", MultiLineChartController);

import BarChartController from "./bar_chart_controller";
application.register("bar-chart", BarChartController);