export const STEPS = {
  INITIAL: 0,
  CONNECTION_ADDRESS: 1,
  CONNECTION_PLACEMENT: 2,
  CONNECTION_TYPE: 3,
  CONNECTION_COST: 4,
  RUN_SPEED_TEST: 5,
  SPEED_TEST_RESULTS: 6,
  NO_INTERNET: 7,
};
