services:
  otel-collector:
    image: registry.staging.radartoolkit.com/otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    networks:
      - public
    environment:
      - AWS_REGION=us-east-2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws

    configs:
      - source: otel_config-v23
        target: /etc/otel-agent-config.yaml

configs:
  # To update config files, we must rename the config key name, and update the service to source from this new name.
  # see for more: https://docs.docker.com/engine/swarm/configs/#example-rotate-a-config
  otel_config-v23:
    template_driver: golang
    file: ./configs/config.yaml

networks:
  public:
    driver: overlay
    attachable: true

