services:
  redis:
    image: redis:7.0.2
    networks:
      - public
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.redis == true

networks:
  public:
    driver: overlay
    attachable: true

volumes:
  redis_data:
