managers:
  hosts:
    radar-swarm-01:
      swarm_default_addr_pool: 10.2.0.0/16 # Be careful to not conflict with the VPC subnet
      labels:
        redis: "true"
        registry: "true"
        prometheus: "true"

workers:
  hosts:
    db.mapping.radartoolkit.com:
      skip_cloudwatch: true
      labels:
        external: "true"
        service: clickhouse
        network: tailscale

postgresql-servers:
  hosts:
    radar-db-01:
  vars:
      listen_address: 10.0.0.0/16
      db_backup_bucket_name: "radar-db-backup-production-new"

clickhousedb:
  hosts:
    db.mapping.radartoolkit.com:
  vars:
    db_name: mlab-mapping
