// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	namespaces "github.com/exactlylabs/mlab-mapping/backend/pkg/app/ports/namespaces"
	mock "github.com/stretchr/testify/mock"

	storages "github.com/exactlylabs/mlab-mapping/backend/pkg/app/ports/storages"
)

// GeospaceStorage is an autogenerated mock type for the GeospaceStorage type
type GeospaceStorage struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx, limit, offset
func (_m *GeospaceStorage) All(ctx context.Context, limit *int, offset *int) (storages.Iterator[*storages.DetailedGeospace], error) {
	ret := _m.Called(ctx, limit, offset)

	var r0 storages.Iterator[*storages.DetailedGeospace]
	if rf, ok := ret.Get(0).(func(context.Context, *int, *int) storages.Iterator[*storages.DetailedGeospace]); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storages.Iterator[*storages.DetailedGeospace])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *int, *int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllFromNamespace provides a mock function with given fields: ctx, namespace, limit, offset
func (_m *GeospaceStorage) AllFromNamespace(ctx context.Context, namespace namespaces.Namespace, limit *int, offset *int) (storages.Iterator[*storages.DetailedGeospace], error) {
	ret := _m.Called(ctx, namespace, limit, offset)

	var r0 storages.Iterator[*storages.DetailedGeospace]
	if rf, ok := ret.Get(0).(func(context.Context, namespaces.Namespace, *int, *int) storages.Iterator[*storages.DetailedGeospace]); ok {
		r0 = rf(ctx, namespace, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storages.Iterator[*storages.DetailedGeospace])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, namespaces.Namespace, *int, *int) error); ok {
		r1 = rf(ctx, namespace, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *GeospaceStorage) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connected provides a mock function with given fields:
func (_m *GeospaceStorage) Connected() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, g
func (_m *GeospaceStorage) Create(ctx context.Context, g *storages.Geospace) error {
	ret := _m.Called(ctx, g)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storages.Geospace) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *GeospaceStorage) Get(ctx context.Context, id string) (*storages.DetailedGeospace, error) {
	ret := _m.Called(ctx, id)

	var r0 *storages.DetailedGeospace
	if rf, ok := ret.Get(0).(func(context.Context, string) *storages.DetailedGeospace); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storages.DetailedGeospace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByGeoId provides a mock function with given fields: ctx, namespace, geoId
func (_m *GeospaceStorage) GetByGeoId(ctx context.Context, namespace namespaces.Namespace, geoId string) (*storages.DetailedGeospace, error) {
	ret := _m.Called(ctx, namespace, geoId)

	var r0 *storages.DetailedGeospace
	if rf, ok := ret.Get(0).(func(context.Context, namespaces.Namespace, string) *storages.DetailedGeospace); ok {
		r0 = rf(ctx, namespace, geoId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storages.DetailedGeospace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, namespaces.Namespace, string) error); ok {
		r1 = rf(ctx, namespace, geoId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Open provides a mock function with given fields:
func (_m *GeospaceStorage) Open() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, query, limit, offset
func (_m *GeospaceStorage) Search(ctx context.Context, query string, limit *int, offset *int) (storages.Iterator[*storages.DetailedGeospace], error) {
	ret := _m.Called(ctx, query, limit, offset)

	var r0 storages.Iterator[*storages.DetailedGeospace]
	if rf, ok := ret.Get(0).(func(context.Context, string, *int, *int) storages.Iterator[*storages.DetailedGeospace]); ok {
		r0 = rf(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storages.Iterator[*storages.DetailedGeospace])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, *int, *int) error); ok {
		r1 = rf(ctx, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchFromNamespace provides a mock function with given fields: ctx, query, namespace, limit, offset
func (_m *GeospaceStorage) SearchFromNamespace(ctx context.Context, query string, namespace namespaces.Namespace, limit *int, offset *int) (storages.Iterator[*storages.DetailedGeospace], error) {
	ret := _m.Called(ctx, query, namespace, limit, offset)

	var r0 storages.Iterator[*storages.DetailedGeospace]
	if rf, ok := ret.Get(0).(func(context.Context, string, namespaces.Namespace, *int, *int) storages.Iterator[*storages.DetailedGeospace]); ok {
		r0 = rf(ctx, query, namespace, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storages.Iterator[*storages.DetailedGeospace])
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, namespaces.Namespace, *int, *int) error); ok {
		r1 = rf(ctx, query, namespace, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, g
func (_m *GeospaceStorage) Update(ctx context.Context, g *storages.Geospace) error {
	ret := _m.Called(ctx, g)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storages.Geospace) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewGeospaceStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewGeospaceStorage creates a new instance of GeospaceStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGeospaceStorage(t mockConstructorTestingTNewGeospaceStorage) *GeospaceStorage {
	mock := &GeospaceStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
