---
- name: Install Cloudwatch Agent
  become: yes
  yum:
    name: amazon-cloudwatch-agent
    state: latest

- name: Configure AWS CloudWatch agent
  become: yes
  template:
    src: cloudwatch_agent_config.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    owner: root
    group: root
    mode: 0644

- name: Start CloudWatch Agent
  become: yes
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
