---
- include_tasks: vector.yml
  when: ansible_os_family == 'Debian' and not skip_vector

- include_tasks: vector.yum.yml
  when: (ansible_os_family == 'RedHat' or ansible_os_family == 'Centos') and not skip_vector

- include_tasks: otel.yml
  when: ansible_os_family == 'Debian' and not skip_otel

- include_tasks: otel.yum.yml
  when: (ansible_os_family == 'RedHat' or ansible_os_family == 'Centos') and not skip_otel

- include_tasks: remove_vector.yml
  when: skip_vector and not skip_otel
