---
- name: Download otelcol-contrib .rpm
  become: yes
  get_url:
    url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v{{ otelcol_contrib_version }}/otelcol-contrib_{{ otelcol_contrib_version }}_linux_{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}.rpm"
    dest: "/tmp/otelcol-contrib_{{ otelcol_contrib_version }}.rpm"

- name: Install otelcol-contrib
  become: yes
  yum:
    name: "/tmp/otelcol-contrib_{{ otelcol_contrib_version }}.rpm"
    state: present
    disable_gpg_check: yes
  register: otel_install

- name: Add otelcol-contrib user to systemd-journal group
  become: yes
  user:
    name: otelcol-contrib
    groups: systemd-journal
    append: yes

- name: Configure otelcol-contrib
  become: yes
  template:
    src: otel-agent-config.yaml.j2
    dest: /etc/otelcol-contrib/config.yaml
    owner: root
    group: root
    mode: 0644
  register: otel_config

- name: Start otelcol-contrib
  become: yes
  service:
    name: otelcol-contrib
    state: started
    enabled: yes
  when: otel_install.changed

- name: Restart otelcol-contrib
  become: yes
  service:
    name: otelcol-contrib
    state: restarted
    enabled: yes
  when: otel_config.changed
