---
- name: Stop and disable Vector
  become: yes
  service:
    name: vector
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Remove Vector package (Debian)
  become: yes
  apt:
    name: vector
    state: absent
  when: ansible_os_family == 'Debian'

- name: Remove Vector package (RedHat)
  become: yes
  yum:
    name: vector
    state: absent
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Centos'

- name: Remove Vector config directory
  become: yes
  file:
    path: /etc/vector
    state: absent
