export type GeographicalCategory = State | County | TribalLand;

export type State = {
  title: string;
  abbreviation: string;
};

export type County = {
  title: string;
  state: State;
};

export type TribalLand = {
  title: string;
  abbreviation: string;
};

export const isState = (item: any): item is State => (item as State) !== undefined;

export const states: Array<State> = [
  {title: 'Alabama', abbreviation: 'AL'},
  {title: 'Alaska', abbreviation: 'AK'},
  {title: 'American Samoa', abbreviation: 'AS'},
  {title: 'Arizona', abbreviation: 'AZ'},
  {title: 'Arkansas', abbreviation: 'AR'},
  {title: 'California', abbreviation: 'CA'},
  {title: 'Colorado', abbreviation: 'CO'},
  {title: 'Connecticut', abbreviation: 'CT'},
  {title: 'Delaware', abbreviation: 'DE'},
  {title: 'District of Columbia', abbreviation: 'DC'},
  {title: 'Federated States of Micronesia', abbreviation: ''},
  {title: 'Florida', abbreviation: 'FL'},
  {title: 'Georgia', abbreviation: 'GA'},
  {title: 'Guam', abbreviation: 'GU'},
  {title: 'Hawaii', abbreviation: 'HI'},
  {title: 'Idaho', abbreviation: 'ID'},
  {title: 'Illinois', abbreviation: 'IL'},
  {title: 'Indiana', abbreviation: 'IN'},
  {title: 'Iowa', abbreviation: 'IA'},
  {title: 'Kansas', abbreviation: 'KS'},
  {title: 'Kentucky', abbreviation: 'KY'},
  {title: 'Louisiana', abbreviation: 'LA'},
  {title: 'Maine', abbreviation: 'ME'},
  {title: 'Marshall Islands', abbreviation: 'MH'},
  {title: 'Maryland', abbreviation: 'MD'},
  {title: 'Massachusetts', abbreviation: 'MA'},
  {title: 'Michigan', abbreviation: 'MI'},
  {title: 'Minnesota', abbreviation: 'MN'},
  {title: 'Mississippi', abbreviation: 'MS'},
  {title: 'Missouri', abbreviation: 'MO'},
  {title: 'Montana', abbreviation: 'MT'},
  {title: 'Nebraska', abbreviation: 'NE'},
  {title: 'Nevada', abbreviation: 'NV'},
  {title: 'New Hampshire', abbreviation: 'NH'},
  {title: 'New Jersey', abbreviation: 'NJ'},
  {title: 'New Mexico', abbreviation: 'NM'},
  {title: 'New York', abbreviation: 'NY'},
  {title: 'North Carolina', abbreviation: 'NC'},
  {title: 'North Dakota', abbreviation: 'ND'},
  {title: 'Northern Mariana Islands', abbreviation: 'MP'},
  {title: 'Ohio', abbreviation: 'OH'},
  {title: 'Oklahoma', abbreviation: 'OK'},
  {title: 'Oregon', abbreviation: 'OR'},
  {title: 'Palau', abbreviation: 'PW'},
  {title: 'Pennsylvania', abbreviation: 'PA'},
  {title: 'Puerto Rico', abbreviation: 'PR'},
  {title: 'Rhode Island', abbreviation: ''},
  {title: 'South Carolina', abbreviation: 'SC'},
  {title: 'South Dakota', abbreviation: 'SD'},
  {title: 'Tennessee', abbreviation: 'TN'},
  {title: 'Texas', abbreviation: 'TX'},
  {title: 'Utah', abbreviation: 'UT'},
  {title: 'Vermont', abbreviation: 'VT'},
  {title: 'Virgin Island', abbreviation: 'VI'},
  {title: 'Virginia', abbreviation: 'VA'},
  {title: 'Washington', abbreviation: 'WA'},
  {title: 'West Virginia', abbreviation: 'WV'},
  {title: 'Wisconsin', abbreviation: 'WI'},
  {title: 'Wyoming', abbreviation: 'WY'},
];

export const counties: Array<County> = [
  {title: 'Autauga County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Baldwin County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Barbour County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Bibb County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Blount County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Bullock County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Butler County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Calhoun County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Chambers County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Cherokee County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Chilton County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Choctaw County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Clarke County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Clay County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Cleburne County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Coffee County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Colbert County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Conecuh County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Coosa County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Covington County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Crenshaw County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Cullman County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Dale County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Dallas County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'DeKalb County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Elmore County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Escambia County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Etowah County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Fayette County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Franklin County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Geneva County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Greene County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Hale County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Henry County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Houston County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Jackson County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Jefferson County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Lamar County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Lauderdale County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Lawrence County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Lee County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Limestone County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Lowndes County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Macon County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Madison County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Marengo County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Marion County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Marshall County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Mobile County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Monroe County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Montgomery County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Morgan County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Perry County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Pickens County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Pike County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Randolph County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Russell County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Saint Clair County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Shelby County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Sumter County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Talladega County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Tallapoosa County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Tuscaloosa County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Walker County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Washington County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Wilcox County', state:{ title: 'Alabama', abbreviation: 'AL'}},
  {title: 'Winston County', state:{ title: 'Alabama', abbreviation: 'AL'}},
];

export const tribalLands = [];