version: "3.8"

services:
  traefik:
    image: "traefik:v3.0"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: traefik_dynamic_v1
        target: /etc/traefik/dynamic/traefik.yml
    command:
      - "--api.insecure=true"
      - "--ping"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.bufferingsize=100"
      - "--accesslog.fields.headers.names.Authorization=drop"
      - "--accesslog.fields.headers.names.Content-Type=keep"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik_public"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=600"
      - "--entrypoints.web.forwardedheaders.trustedips=10.5.0.0/16"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=600"
      - "--entrypoints.websecure.forwardedheaders.trustedips=10.5.0.0/16"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=devops@exactlylabs.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - target: 80
        published: 80
        protocol: tcp
        # IMPORTANT: Because of how Swarm network mesh, Traefik can't know the real client IP. It'll always think it's a swarm internal IP.
        #  Given it doesn't support the Proxy Protocol, the only way out is to expose Traefik in host mode, meaning it's only accessible through the machine it's hosted in.
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "8080:8080"
    volumes:
      - "letsencrypt-data:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
      - vector_public
      - otel-collector_public

networks:
  public:
    driver: overlay
    attachable: true
  vector_public:
    external: true
  otel-collector_public:
    external: true

volumes:
  letsencrypt-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=nfs.radartoolkit.com,rw
      device: ":/mnt/nfs/traefik/letsencrypt"

configs:
  # To update config files, we must rename the config key name, and update the service to source from this new name.
  # see for more: https://docs.docker.com/engine/swarm/configs/#example-rotate-a-config
  traefik_dynamic_v1:
    template_driver: golang
    file: ./configs/dynamic.yml
