# Took from https://github.com/AlexeySetevoi/ansible-clickhouse/blob/master/tasks/params.yml
---

- name: "Set clickhouse_service_enable"
  set_fact:
    clickhouse_service_enable: "{{ false if clickhouse_remove else true }}"

- name: "Set clickhouse_service_ensure"
  set_fact:
    clickhouse_service_ensure: "{{ 'stopped' if clickhouse_remove else 'started' }}"
