# Took from https://github.com/AlexeySetevoi/ansible-clickhouse/blob/master/tasks/precheck.yml
- name: Requirements check | Checking sse4_2 support
  command: grep -q sse4_2 /proc/cpuinfo
  changed_when: False
