services:
  app: &base
    image: registry.radartoolkit.com/pods-server:latest
    healthcheck:
      test: "curl --fail http://localhost:3000/health || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DISABLE_SPRING=1
      - RAILS_MAX_THREADS=10
      - SENTRY_HOST=o1197382.ingest.sentry.io
      - SENTRY_PROJECT_ID=6320151
      - BUCKET_NAME=radar-pods-production
      - BUCKET_ACCESS_KEY=004049506844ea70000000001
      - HEALTHCHECK_URL=https://pods.radartoolkit.com/health
      - WEB_CONCURRENCY=2
      - REDIS_URL=redis://redis:6379
      - TAILSCALE_CLIENT_ID=kBsnYW5CNTRL
      - DB_MAX_POOL_SIZE=20
      - CORS_ALLOWED_ORIGINS=https://speed.exactlylabs.com,https://speedtest.exactlylabs.com,https://speed.radartoolkit.com,https://www.speed.radartoolkit.com
      - RAILS_LOG_TO_STDOUT=true
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1043252076664332300/N7I1yHxPvnoifPE0xnrmlgXv8dGrTSvqoOnDx1fwE7gUJ86GNHdD6cGtXuQVbOauNT9P
      - EVENTS_NOTIFIER_DISCORD_TBP_ALERTS_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_TBP_GENERAL_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_WEBHOOK=https://discord.com/api/webhooks/1072323113544589322/Rlc2mlNd1K_s0p0_KhoUW6DTNLvPXO041FAh9kPfZ8EytAP2ffIdQrs0Z6Tq4y7WQd3D
      - FIPS_GEOCODER_URL=http://fipsgeocoder_api:5000
      - PUBLIC_PAGE_SUBMISSION_EMAILS=matt@exactlylabs.com,amanda@exactlylabs.com,anand@exactlylabs.com
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318/v1/traces
    secrets:
      - source: PODS_GEOAPIFY_KEY
        target: GEOAPIFY_KEY
      - source: PODS_BUCKET_SECRET_KEY
        target: BUCKET_SECRET_KEY
      - source: PODS_SECRET_KEY
        target: SECRET_KEY_BASE
      - source: PODS_SMTP_PASSWORD
        target: SMTP_PASSWORD
      - source: PODS_DATABASE_URL
        target: DATABASE_URL
      - source: PODS_AMPLITUDE_API_KEY
        target: AMPLITUDE_API_KEY
      - source: PODS_BETTERSTACK_STATUS_CRON_KEY
        target: BETTERSTACK_STATUS_CRON_KEY
      - source: PODS_BETTERSTACK_TESTS_CRON_KEY
        target: BETTERSTACK_TESTS_CRON_KEY
      - source: PODS_TAILSCALE_CLIENT_SECRET
        target: TAILSCALE_CLIENT_SECRET

    networks:
      - traefik_public
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.labels.network == aws
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pods-server-app.rule=Host(`pods.radartoolkit.com`) || Host(`radar.exactlylabs.com`)"
        - "traefik.http.services.pods-server-app.loadbalancer.server.port=3000"
        - "traefik.http.routers.pods-server-app.entrypoints=web,websecure"
        - "traefik.http.routers.pods-server-app.tls.certresolver=myresolver"
        - "traefik.http.middlewares.forward-headers.headers.sslredirect=true"
        - "traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.ssl-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.ssl-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.pods-server-app.middlewares=ssl-redirect@swarm,forward-headers@swarm"

  worker:
    image: registry.radartoolkit.com/pods-server:latest
    command: ["./bin/bundle", "exec", "sidekiq"]
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DISABLE_SPRING=1
      - RAILS_MAX_THREADS=10
      - SENTRY_HOST=o1197382.ingest.sentry.io
      - SENTRY_PROJECT_ID=6320151
      - BUCKET_NAME=radar-pods-production
      - BUCKET_ACCESS_KEY=004049506844ea70000000001
      - HEALTHCHECK_URL=https://pods.radartoolkit.com/health
      - WEB_CONCURRENCY=4
      - REDIS_URL=redis://redis:6379
      - TAILSCALE_CLIENT_ID=kBsnYW5CNTRL
      - DB_MAX_POOL_SIZE=40
      - CORS_ALLOWED_ORIGINS=https://speed.exactlylabs.com,https://speedtest.exactlylabs.com,https://speed.radartoolkit.com,https://www.speed.radartoolkit.com
      - RAILS_LOG_TO_STDOUT=true
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1043252076664332300/N7I1yHxPvnoifPE0xnrmlgXv8dGrTSvqoOnDx1fwE7gUJ86GNHdD6cGtXuQVbOauNT9P
      - EVENTS_NOTIFIER_DISCORD_TBP_ALERTS_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_TBP_GENERAL_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_WEBHOOK=https://discord.com/api/webhooks/1072323113544589322/Rlc2mlNd1K_s0p0_KhoUW6DTNLvPXO041FAh9kPfZ8EytAP2ffIdQrs0Z6Tq4y7WQd3D
      - FIPS_GEOCODER_URL=http://fipsgeocoder_api:5000
      - PUBLIC_PAGE_SUBMISSION_EMAILS=matt@exactlylabs.com,amanda@exactlylabs.com,anand@exactlylabs.com
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318/v1/traces
    secrets:
      - source: PODS_GEOAPIFY_KEY
        target: GEOAPIFY_KEY
      - source: PODS_BUCKET_SECRET_KEY
        target: BUCKET_SECRET_KEY
      - source: PODS_SECRET_KEY
        target: SECRET_KEY_BASE
      - source: PODS_SMTP_PASSWORD
        target: SMTP_PASSWORD
      - source: PODS_DATABASE_URL
        target: DATABASE_URL
      - source: PODS_AMPLITUDE_API_KEY
        target: AMPLITUDE_API_KEY
      - source: PODS_BETTERSTACK_STATUS_CRON_KEY
        target: BETTERSTACK_STATUS_CRON_KEY
      - source: PODS_BETTERSTACK_TESTS_CRON_KEY
        target: BETTERSTACK_TESTS_CRON_KEY
      - source: PODS_TAILSCALE_CLIENT_SECRET
        target: TAILSCALE_CLIENT_SECRET
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public

    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2024M
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.labels.network == aws
      labels: []

  clock:
    image: registry.radartoolkit.com/pods-server:latest
    command: ["./bin/rails", "runner", "clock.rb"]
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DISABLE_SPRING=1
      - RAILS_MAX_THREADS=10
      - SENTRY_HOST=o1197382.ingest.sentry.io
      - SENTRY_PROJECT_ID=6320151
      - BUCKET_NAME=radar-pods-production
      - BUCKET_ACCESS_KEY=004049506844ea70000000001
      - HEALTHCHECK_URL=https://pods.radartoolkit.com/health
      - WEB_CONCURRENCY=4
      - REDIS_URL=redis://redis:6379
      - TAILSCALE_CLIENT_ID=kBsnYW5CNTRL
      - DB_MAX_POOL_SIZE=10
      - CORS_ALLOWED_ORIGINS=https://speed.exactlylabs.com,https://speedtest.exactlylabs.com,https://speed.radartoolkit.com,https://www.speed.radartoolkit.com
      - RAILS_LOG_TO_STDOUT=true
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1043252076664332300/N7I1yHxPvnoifPE0xnrmlgXv8dGrTSvqoOnDx1fwE7gUJ86GNHdD6cGtXuQVbOauNT9P
      - EVENTS_NOTIFIER_DISCORD_TBP_ALERTS_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_TBP_GENERAL_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_WEBHOOK=https://discord.com/api/webhooks/1072323113544589322/Rlc2mlNd1K_s0p0_KhoUW6DTNLvPXO041FAh9kPfZ8EytAP2ffIdQrs0Z6Tq4y7WQd3D
      - FIPS_GEOCODER_URL=http://fipsgeocoder_api:5000
      - PUBLIC_PAGE_SUBMISSION_EMAILS=matt@exactlylabs.com,amanda@exactlylabs.com,anand@exactlylabs.com
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318/v1/traces
    secrets:
      - source: PODS_GEOAPIFY_KEY
        target: GEOAPIFY_KEY
      - source: PODS_BUCKET_SECRET_KEY
        target: BUCKET_SECRET_KEY
      - source: PODS_SECRET_KEY
        target: SECRET_KEY_BASE
      - source: PODS_SMTP_PASSWORD
        target: SMTP_PASSWORD
      - source: PODS_DATABASE_URL
        target: DATABASE_URL
      - source: PODS_AMPLITUDE_API_KEY
        target: AMPLITUDE_API_KEY
      - source: PODS_BETTERSTACK_STATUS_CRON_KEY
        target: BETTERSTACK_STATUS_CRON_KEY
      - source: PODS_BETTERSTACK_TESTS_CRON_KEY
        target: BETTERSTACK_TESTS_CRON_KEY
      - source: PODS_TAILSCALE_CLIENT_SECRET
        target: TAILSCALE_CLIENT_SECRET
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels: []

  mobile_scanner:
    image: registry.radartoolkit.com/pods-server:latest
    command: ["./bin/bundle", "exec", "sidekiq", "-q mobile_scans"]
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DISABLE_SPRING=1
      - RAILS_MAX_THREADS=10
      - SENTRY_HOST=o1197382.ingest.sentry.io
      - SENTRY_PROJECT_ID=6320151
      - BUCKET_NAME=radar-pods-production
      - BUCKET_ACCESS_KEY=004049506844ea70000000001
      - HEALTHCHECK_URL=https://pods.radartoolkit.com/health
      - WEB_CONCURRENCY=4
      - REDIS_URL=redis://redis:6379
      - TAILSCALE_CLIENT_ID=kBsnYW5CNTRL
      - DB_MAX_POOL_SIZE=10
      - CORS_ALLOWED_ORIGINS=https://speed.exactlylabs.com,https://speedtest.exactlylabs.com,https://speed.radartoolkit.com,https://www.speed.radartoolkit.com
      - RAILS_LOG_TO_STDOUT=true
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1043252076664332300/N7I1yHxPvnoifPE0xnrmlgXv8dGrTSvqoOnDx1fwE7gUJ86GNHdD6cGtXuQVbOauNT9P
      - EVENTS_NOTIFIER_DISCORD_TBP_ALERTS_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_TBP_GENERAL_WEBHOOK=https://discord.com/api/webhooks/1105259429038919680/AZpyQ5AnJzODDC27CPG4BrDLjHzAxIRB-49zwestk9ixjdB31G9ZlpsJaVjp1qYlJPmB
      - EVENTS_NOTIFIER_DISCORD_WEBHOOK=https://discord.com/api/webhooks/1072323113544589322/Rlc2mlNd1K_s0p0_KhoUW6DTNLvPXO041FAh9kPfZ8EytAP2ffIdQrs0Z6Tq4y7WQd3D
      - FIPS_GEOCODER_URL=http://fipsgeocoder_api:5000
      - PUBLIC_PAGE_SUBMISSION_EMAILS=matt@exactlylabs.com,amanda@exactlylabs.com,anand@exactlylabs.com
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318/v1/traces
    secrets:
      - source: PODS_GEOAPIFY_KEY
        target: GEOAPIFY_KEY
      - source: PODS_BUCKET_SECRET_KEY
        target: BUCKET_SECRET_KEY
      - source: PODS_SECRET_KEY
        target: SECRET_KEY_BASE
      - source: PODS_SMTP_PASSWORD
        target: SMTP_PASSWORD
      - source: PODS_DATABASE_URL
        target: DATABASE_URL
      - source: PODS_AMPLITUDE_API_KEY
        target: AMPLITUDE_API_KEY
      - source: PODS_BETTERSTACK_STATUS_CRON_KEY
        target: BETTERSTACK_STATUS_CRON_KEY
      - source: PODS_BETTERSTACK_TESTS_CRON_KEY
        target: BETTERSTACK_TESTS_CRON_KEY
      - source: PODS_TAILSCALE_CLIENT_SECRET
        target: TAILSCALE_CLIENT_SECRET
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels: []

networks:
  traefik_public:
    external: true
  fipsgeocoder_public:
    external: true
  redis_public:
    external: true
  otel-collector_public:
    external: true

secrets:
  PODS_GEOAPIFY_KEY:
    external: true
  PODS_BUCKET_SECRET_KEY:
    external: true
  PODS_SECRET_KEY:
    external: true
  PODS_SMTP_PASSWORD:
    external: true
  PODS_DATABASE_URL:
    external: true
  PODS_GCP_DATABASE_URL:
    external: true
  PODS_AMPLITUDE_API_KEY:
    external: true
  PODS_BETTERSTACK_STATUS_CRON_KEY:
    external: true
  PODS_BETTERSTACK_TESTS_CRON_KEY:
    external: true
  PODS_TAILSCALE_CLIENT_SECRET:
    external: true



