services:
  app: &base
    image: registry.staging.radartoolkit.com/pods-server:latest
    environment:
      - RAILS_ENV=staging
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MAX_THREADS=10
      - SENTRY_HOST=o1197382.ingest.sentry.io
      - SENTRY_PROJECT_ID=6320151
      - DB_MAX_POOL_SIZE=20
      - BUCKET_NAME=radar-pods-staging
      - BUCKET_ACCESS_KEY=004049506844ea70000000001
      - HEALTHCHECK_URL=https://pods.staging.radartoolkit.com/health
      - WEB_CONCURRENCY=2
      - REDIS_URL=redis://redis:6379
      - TAILSCALE_CLIENT_ID=kBsnYW5CNTRL
      - DB_MAX_POOL_SIZE=40
      - CORS_ALLOWED_ORIGINS=https://speed.staging.exactlylabs.com,https://speedtest.staging.exactlylabs.com,https://speed.staging.radartoolkit.com,https://www.speed.staging.radartoolkit.com
      - RAILS_LOG_TO_STDOUT=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318

    secrets:
      - source: PODS_GEOAPIFY_KEY
        target: GEOAPIFY_KEY
      - source: PODS_BUCKET_SECRET_KEY
        target: BUCKET_SECRET_KEY
      - source: PODS_SECRET_KEY
        target: SECRET_KEY_BASE
      - source: PODS_SMTP_PASSWORD
        target: SMTP_PASSWORD
      - source: PODS_DATABASE_URL
        target: DATABASE_URL
    networks:
      - traefik_public
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pods-server-app.rule=Host(`pods-swarm.staging.radartoolkit.com`) || Host(`pods.staging.radartoolkit.com`) || Host(`radar-staging.exactlylabs.com`) || Host(`radar.staging.exactlylabs.com`)"
        - "traefik.http.services.pods-server-app.loadbalancer.server.port=3000"
        - "traefik.http.routers.pods-server-app.entrypoints=web,websecure"
        - "traefik.http.routers.pods-server-app.tls.certresolver=myresolver"
        - "traefik.http.middlewares.forward-headers.headers.sslredirect=true"
        - "traefik.http.middlewares.forward-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.ssl-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.ssl-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.pods-server-app.middlewares=ssl-redirect@swarm,forward-headers@swarm"

  worker:
    <<: *base
    command: ["./bin/bundle", "exec", "sidekiq"]
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      labels: []

  clock:
    <<: *base
    command: ["./bin/rails", "runner", "clock.rb"]
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels: []

  mobile_scanner:
    <<: *base
    command: ["./bin/bundle", "exec", "sidekiq", "-q mobile_scans"]
    networks:
      - fipsgeocoder_public
      - redis_public
      - otel-collector_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      labels: []

networks:
  traefik_public:
    external: true
  fipsgeocoder_public:
    external: true
  redis_public:
    external: true
  otel-collector_public:
    external: true

secrets:
  PODS_GEOAPIFY_KEY:
    external: true
  PODS_BUCKET_SECRET_KEY:
    external: true
  PODS_SECRET_KEY:
    external: true
  PODS_SMTP_PASSWORD:
    external: true
  PODS_DATABASE_URL:
    external: true

