---
- name: Backup pg_hba.conf
  become: yes
  copy:
    src: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf"
    remote_src: true
    dest: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf.bkp"

- name: Configure pg_hba.conf
  become: yes
  template:
    src: "{{postgresql_pg_hba_template}}"
    dest: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: 0600
  notify:
    - reload postgresql service

- name: Configure postgresql.conf
  become: yes
  template:
    src: "{{postgresql_configuration_template}}"
    dest: "/etc/postgresql/{{postgresql_version}}/main/conf.d/ansible-config.conf"
    owner: "postgres"
    group: "postgres"
    mode: 0600
  notify:
    - reload postgresql service
