---
- name: Create Data Directory
  become: yes
  file:
    path: "{{postgresql_data_directory}}"
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: 0700
  when: "postgresql_data_directory != '/var/lib/postgresql/'+postgresql_version+'/main'"
  register: create_data

- name: Copy Data Directory Content
  become: yes
  shell: "cp -axf /var/lib/postgresql/{{postgresql_version}}/main/* {{postgresql_data_directory}}"
  when: "create_data.changed"
  notify:
    - restart postgresql service

- name: Backup pg_hba.conf
  become: yes
  copy:
    src: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf"
    remote_src: true
    dest: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf.bkp"

- name: Configure pg_hba.conf
  become: yes
  template:
    src: "{{postgresql_pg_hba_template}}"
    dest: "/etc/postgresql/{{postgresql_version}}/main/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: 0600
  notify:
    - restart postgresql service

- name: Configure postgresql.conf
  become: yes
  template:
    src: "{{postgresql_configuration_template}}"
    dest: "/etc/postgresql/{{postgresql_version}}/main/conf.d/ansible-config.conf"
    owner: "postgres"
    group: "postgres"
    mode: 0600
  notify:
    - restart postgresql service

- name: Configure Data Directory in postgresql.conf
  become: yes
  lineinfile:
    dest: "/etc/postgresql/{{postgresql_version}}/main/postgresql.conf"
    regexp: "data_directory ="
    line: "data_directory = '{{postgresql_data_directory}}'"
    state: present
  notify:
    - restart postgresql service

- name: Install ACL and Psycopg2 for Python
  become: yes
  apt:
    name:
      - python3-psycopg2
      - acl
    state: latest
    update_cache: yes

- name: Setup PostgreSQL User
  become: true
  become_user: postgres
  postgresql_user:
    db: postgres
    name: "{{item.name}}"
    password: "{{item.password}}"
    role_attr_flags: "{{item.permissions}}"
  loop: "{{postgresql_users}}"
