---
- name: "Install Requirements"
  become: yes
  apt:
    name:
      - curl
      - ca-certificates
    state: latest
    update_cache: yes

- name: "Setup APT Keys"
  become: yes
  block:
    - name: create gpg key path
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory

    - name: grab Postgres gpg key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    - name: add Postgres repository
      apt_repository:
        repo: deb [arch={% if ansible_architecture == "aarch64" %}arm64{% else %}{{ansible_architecture}}{% endif %} signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present

- name: Install Postgres
  become: yes
  apt:
    name:
      - "postgresql-{{postgresql_version}}"
      - "postgis"

- name: Create Data Directory
  become: yes
  file:
    path: "{{postgresql_data_directory}}"
    state: directory
    owner: "postgres"
    group: "postgres"
    mode: 0700
  when: "postgresql_data_directory != '/var/lib/postgresql/'+postgresql_version+'/main'"
  register: create_data

- name: Copy Data Directory Content
  become: yes
  shell: "cp -axf /var/lib/postgresql/{{postgresql_version}}/main/* {{postgresql_data_directory}}"
  when: "create_data.changed"
  notify:
    - restart postgresql service

- name: Configure Data Directory in postgresql.conf
  become: yes
  lineinfile:
    dest: "/etc/postgresql/{{postgresql_version}}/main/postgresql.conf"
    regexp: "data_directory ="
    line: "data_directory = '{{postgresql_data_directory}}'"
    state: present
  notify:
    - restart postgresql service
