---
- name: "Install Requirements"
  become: yes
  apt:
    name:
      - curl
      - ca-certificates
    state: latest
    update_cache: yes

- name: "Setup APT Keys"
  become: yes
  block:
    - name: create gpg key path
      file:
        path: /usr/share/postgresql-common/pgdg
        state: directory

    - name: grab Postgres gpg key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    - name: add Postgres repository
      apt_repository:
        repo: deb [arch={% if ansible_architecture == "aarch64" %}arm64{% else %}{{ansible_architecture}}{% endif %} signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present

- name: Install Postgres
  become: yes
  apt:
    name:
      - "postgresql-{{postgresql_version}}"
      - "postgis"
