---
- include_tasks: install.apt.yml
  when: ansible_os_family in ['Debian', 'Ubuntu'] and not skip_postgres and not skip_install

- include_tasks: users.yml
  when: not skip_postgres and not skip_users

- include_tasks: configure.yml
  when: not skip_postgres and not skip_config

- include_tasks: pgbackrest.yml
  when: ansible_os_family in ['Debian', 'Ubuntu'] and not skip_pgbackrest
