---
- name: Install PGBackRest
  become: yes
  apt:
    name:
      - pgbackrest
      - cron
    state: present

- name: Configure PGBackRest
  become: yes
  template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest.conf
    owner: postgres
    group: postgres
    mode: 0640

- name: Create the Stanza
  become: yes
  become_method: sudo
  become_user: postgres
  shell: pgbackrest --stanza=radar --log-level-console=info stanza-create

- name: Check the Configuration
  become: yes
  become_method: sudo
  become_user: postgres
  shell: pgbackrest --stanza=radar --log-level-console=info check
  notify:
    - restart postgresql service

- name: Schedule Full Backup on Sundays
  become: yes
  ansible.builtin.cron:
    name: "Full Backup"
    weekday: "0"
    hour: "24"
    minute: "0"
    user: postgres
    job: "pgbackrest --type=full --stanza=radar backup"

- name: Schedule Daily Diff Backups from Monday to Saturday
  become: yes
  ansible.builtin.cron:
    name: "Diff Backup"
    weekday: "1-6"
    hour: "24"
    minute: "0"
    user: postgres
    job: "pgbackrest --type=diff --stanza=radar backup"
