services:
  app:
    image: quay.io/prometheuscommunity/postgres-exporter
    command:
      - "--collector.stat_statements"
      - "--collector.statio_user_tables"
      - "--collector.statio_user_indexes"
    ports:
      - 9187:9187
    networks:
      - prometheus_public
    environment:
      - DATA_SOURCE_URI=db-01.radartoolkit.com/radar
      - DATA_SOURCE_USER=prometheus
      - DATA_SOURCE_PASS_FILE=/run/secrets/PMT_POSTGRESQL_EXPORTER_PASSWORD
    secrets:
      - PMT_POSTGRESQL_EXPORTER_PASSWORD
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.network == aws
      resources:
        limits:
          memory: 512M

secrets:
  PMT_POSTGRESQL_EXPORTER_PASSWORD:
    external: true

networks:
  prometheus_public:
    external: true
