- name: "Install Clickhouse"
  hosts: clickhousedb
  become: yes
  vars:
    clickhouse_users_custom:
      - { name: "{{ db_user }}", password_sha256_hex: "{{ db_password_sha256 }}", profile: "default"}
    clickhouse_dbs_custom:
      - { name: "{{ db_name }}", state: present }
    clickhouse_profiles_custom:
      default:
        max_bytes_before_external_group_by: 10000000000
        load_balancing: random
    clickhouse_listen_host_custom:
      - "0.0.0.0"
  roles:
    - ansible-clickhouse
