version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.1.0

jobs:
  build-android:
    working_directory: ~/repo/mobile_client_app/client_mobile_app
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - run: flutter build apk --flavor dev -t lib/main_dev.dart
  
  build-ios:
    working_directory: ~/repo/mobile_client_app/client_mobile_app
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run: flutter build api --flavor dev -t lib/main_dev.dart

workflows:
  test_build:
    jobs:
      - flutter/unit_test:
          working_directory: ~/repo/mobile_client_app/client_mobile_app
          version: 3.3.1
      - build-android
      - build-ios
