version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@1.1.0

jobs:
  build-android:
    working_directory: ~/project
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gradle:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: cd ~/project/mobile_client_app/client_mobile_app && flutter build apk --flavor dev -t lib/main_dev.dart
  
  build-ios:
    working_directory: ~/project
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_pod:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: cd ~/project/mobile_client_app/client_mobile_app && flutter build api --flavor dev -t lib/main_dev.dart

workflows:
  test_build:
    jobs:
      - flutter/unit_test:
          app-dir: ~/project/mobile_client_app/client_mobile_app
          version: 3.3.1
      - build-android
      - build-ios
