version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0
  gcp-cli: circleci/gcp-cli@2.4.1
  ruby: circleci/ruby@2.0.0

commands:
  setup_keystores:
    parameters:
      working_directory:
        type: string
        default: "."
    steps:
      - run: echo ${FLUTTER_ANDROID_DEV_KEYSTORE} | base64 -d > << parameters.working_directory >>/upload-dev-keystore.jks
      - run: echo ${FLUTTER_ANDROID_DEV_KEY_PROPERTIES} | base64 -d > << parameters.working_directory >>/key.dev.properties
      - run: echo ${FLUTTER_ANDROID_STAGING_KEYSTORE} | base64 -d > << parameters.working_directory >>/upload-staging-keystore.jks
      - run: echo ${FLUTTER_ANDROID_STAGING_KEY_PROPERTIES} | base64 -d > << parameters.working_directory >>/key.staging.properties
      - run: echo ${FLUTTER_ANDROID_PROD_KEYSTORE} | base64 -d > << parameters.working_directory >>/upload-prod-keystore.jks
      - run: echo ${FLUTTER_ANDROID_PROD_KEY_PROPERTIES} | base64 -d > << parameters.working_directory >>/key.properties

  build-android:
    parameters:
      flavor:
        type: enum
        enum: ["dev","staging", "prod"]
    steps:
      - setup_keystores:
          working_directory: ~/project/mobile_client_app/client_mobile_app/android
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gradle:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: 
          command: ./scripts/build_android_<<  parameters.flavor >>.sh
          working_directory: ~/project/mobile_client_app/client_mobile_app

  setup_provisioning_profiles:
    steps:
      - run: sudo mkdir -p "/Library/MobileDevice/Provisioning Profiles"
      - run: echo ${FLUTTER_IOS_STAGING_PROVISIONING_PROFILE} | base64 -d | sudo tee "/Library/MobileDevice/Provisioning Profiles/Radar_Staging_Distribution.mobileprovision" &>/dev/null
      - run: echo ${FLUTTER_IOS_PROD_PROVISIONING_PROFILE} | base64 -d | sudo tee "/Library/MobileDevice/Provisioning Profiles/Exactly_Labs_Provisioning.mobileprovision" &>/dev/null
      - run: echo ${FLUTTER_IOS_DEV_PROVISIONING_PROFILE} | base64 -d | sudo tee "/Library/MobileDevice/Provisioning Profiles/Radar_Dev_AdHoc.mobileprovision" &>/dev/null
      - run: echo "${FLUTTER_IOS_DISTRIBUTION_CERT}" | base64 -d > /tmp/distribution_dev.cer
      - run: echo ${FLUTTER_IOS_DISTRIBUTION_KEY} | base64 -d > /tmp/distribution_dev.p12
      - run: echo "${FLUTTER_IOS_DISTRIBUTION_CERT}" | base64 -d > /tmp/distribution_staging.cer
      - run: echo ${FLUTTER_IOS_DISTRIBUTION_KEY} | base64 -d > /tmp/distribution_staging.p12
      - run: echo ${ANTHC_FLUTTER_IOS_DISTRIBUTION_CERT} | base64 -d > /tmp/distribution_prod.cer
      - run: echo ${ANTHC_FLUTTER_IOS_DISTRIBUTION_KEY} | base64 -d > /tmp/distribution_prod.p12

jobs:
  build-android:
    working_directory: ~/project
    parameters:
      flavor:
        type: enum
        enum: ["dev", "staging", "prod"]
    executor:
      name: android/android-docker
      tag: 2022.09.1
    steps:
      - checkout
      - build-android:
          flavor: << parameters.flavor >>
      - persist_to_workspace:
          root: ~/project/mobile_client_app/client_mobile_app/workspace
          paths:
            - android/*

  upload-android:
    executor: gcp-cli/google
    steps:
      - attach_workspace:
          at: ~/workspace
      - gcp-cli/initialize:
          gcloud-service-key: FLUTTER_STORAGE_UPLOAD_GCP_CRED
          google-project-id: TTAC_PROD_PROJECT_ID
      - run: gsutil cp -r ~/workspace/android/* gs://${FLUTTER_FLAVORS_BUCKET_NAME}/android
  
  release-android:
    working_directory: ~/project
    docker:
      - image: "cimg/ruby:3.0.2"
    parameters:
      flavor:
        type: enum
        enum: ["staging", "prod"]
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - ruby/install-deps:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run:
          command: gem install fastlane
          working_directory: ~/project/mobile_client_app/client_mobile_app
      - run:
          command: echo ${FLUTTER_ANDROID_DEV_RELEASE_GCP_CREDENTIAL} | base64 -d > /tmp/android_staging_gcpkey.json
      - run:
          command: echo ${FLUTTER_ANDROID_PROD_RELEASE_GCP_CREDENTIAL} | base64 -d > /tmp/android_prod_gcpkey.json
      - run:
          command: |
            ANDROID_AAB_PATH=$(ls ~/workspace/android/<< parameters.flavor >>/*.aab) \
            FASTLANE_GCP_JSONKEY_PATH="/tmp/android_<< parameters.flavor >>_gcpkey.json" \
            fastlane release_<< parameters.flavor >>
          working_directory: ~/project/mobile_client_app/client_mobile_app/android

  build-ios:
    working_directory: ~/project
    macos:
      xcode: 13.4.1
    parameters:
      flavor:
        type: enum
        enum: ["dev", "staging", "prod"]
    steps:
      - checkout
      - setup_provisioning_profiles
      - run: |
          P12_KEY_PATH=/tmp/distribution_<< parameters.flavor>>.p12 \
          CERT_PATH=/tmp/distribution_<< parameters.flavor>>.cer \
          ~/project/mobile_client_app/client_mobile_app/scripts/setup_keychain.sh
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_pod:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: 
          command: ./scripts/build_ios_<<  parameters.flavor >>.sh
          working_directory: ~/project/mobile_client_app/client_mobile_app
      - persist_to_workspace:
          root: ~/project/mobile_client_app/client_mobile_app/workspace
          paths:
            - ios/*

  upload-ios:
    executor: gcp-cli/google
    steps:
      - attach_workspace:
          at: ~/workspace
      - gcp-cli/initialize:
          gcloud-service-key: FLUTTER_STORAGE_UPLOAD_GCP_CRED
          google-project-id: TTAC_PROD_PROJECT_ID
      - run: gsutil cp -r ~/workspace/ios/* gs://${FLUTTER_FLAVORS_BUCKET_NAME}/ios

  release-ios:
    working_directory: ~/project
    macos:
      xcode: 13.4.1
    parameters:
      flavor:
        type: enum
        enum: ["staging", "prod"]
      issuer_id:
        type: string
        default: ${APP_STORE_CONNECT_API_KEY_ISSUER_ID}
      key_key:
        type: string
        default: ${APP_STORE_CONNECT_API_KEY_KEY}
      key_id:
        type: string
        default: ${APP_STORE_CONNECT_API_KEY_KEY_ID}
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - ruby/install-deps:
          app-dir: ~/project/mobile_client_app/client_mobile_app/ios
      - run:
          command: gem install fastlane
          working_directory: ~/project/mobile_client_app/client_mobile_app/ios
      - run:
          command: cp ~/workspace/ios/<< parameters.flavor >>/*.ipa ~/project/mobile_client_app/client_mobile_app/ios/Runner.ipa
          working_directory: ~/project/mobile_client_app/client_mobile_app/ios
      - run:
          command: |
            APP_STORE_CONNECT_API_KEY_ISSUER_ID=<< parameters.issuer_id >> \
            APP_STORE_CONNECT_API_KEY_KEY=<< parameters.key_key >> \
            APP_STORE_CONNECT_API_KEY_KEY_ID=<< parameters.key_id >> \
            fastlane release_<< parameters.flavor >>
          working_directory: ~/project/mobile_client_app/client_mobile_app/ios


workflows:
  mobile_app:
    jobs:
      - flutter/unit_test:
          name: "unit_test"
          app-dir: ~/project/mobile_client_app/client_mobile_app
          version: 3.3.1
      
      # Android
      # Build Flavors
      - build-android:
          name: "build-android-dev"
          requires: [unit_test]
          flavor: dev
          filters:
            branches:
              ignore: ["master"]
      - build-android:
          name: "build-android-staging"
          requires: [unit_test]
          flavor: staging
          filters:
            branches:
              only: "master"
      - build-android:
          name: "build-android-prod"
          requires: [unit_test]
          flavor: prod
          filters:
            branches:
              only: /.*/ # TODO: change back to ignore
            tags:
              only: "/^v.*/"
      ## Upload Flavors to Storage
      - upload-android:
          requires: [build-android-dev, build-android-staging, build-android-prod]
      ## Release Stag/Prod Flavors
      - release-android:
          name: "release-android-staging"
          requires: [build-android-staging]
          flavor: staging
          filters:
            branches:
              only: "master"
      - release-android:
          name: "release-android-prod"
          requires: [build-android-prod]
          flavor: prod
          filters:
            branches:
              only: /.*/ # TODO: change back to ignore
            tags:
              only: "/^v.*/"
    
      # iOS
      # Build Flavors
      - build-ios:
          name: "build-ios-dev"
          requires: [unit_test]
          flavor: dev
          filters:
            branches:
              ignore: "master"
      - build-ios:
          name: "build-ios-staging"
          requires: [unit_test]
          flavor: staging
          filters:
            branches:
              only: "master"
      - build-ios:
          name: "build-ios-prod"
          requires: [unit_test]
          flavor: prod
          filters:
            branches:
              only: /.*/ # TODO: change back to ignore
            tags:
              only: "/^v.*/"
      ## Upload Flavors to Storage
      - upload-ios:
          requires: [build-ios-dev, build-ios-staging, build-ios-prod]
      ## Release Stag/Prod Flavors
      - release-ios:
          name: "release-ios-staging"
          requires: [build-ios-staging]
          flavor: staging
          filters:
            branches:
              only: "master"
      - release-ios:
          name: "release-ios-prod"
          requires: [build-ios-prod]
          flavor: prod
          issuer_id: ${ANTHC_APP_STORE_CONNECT_API_KEY_ISSUER_ID}
          key_key: ${ANTHC_APP_STORE_CONNECT_API_KEY_KEY}
          key_id: ${ANTHC_APP_STORE_CONNECT_API_KEY_KEY_ID}
          filters:
            branches:
              only: /.*/ # TODO: change back to ignore
            tags:
              only: "/^v.*/"
