version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0
  gcp-cli: circleci/gcp-cli@2.4.1
  ruby: circleci/ruby@2.0.0

commands:
  setup_keystores:
    parameters:
      working_directory:
        type: string
        default: "."
    steps:
      - run: echo ${FLUTTER_DEV_KEYSTORE} | base64 -d > /tmp/upload-dev-keystore.jks
      - run: |
          echo """
          storePassword=${FLUTTER_DEV_KEYSTORE_PASSWORD}
          keyPassword=${FLUTTER_DEV_KEYSTORE_PASSWORD}
          keyAlias=upload
          storeFile=/tmp/upload-dev-keystore.jks
          """ > << parameters.working_directory >>/key.dev.properties
      - run: echo ${FLUTTER_PROD_KEYSTORE} | base64 -d > /tmp/upload-keystore.jks
      - run: |
          echo """
          storePassword=${FLUTTER_PROD_KEYSTORE_PASSWORD}
          keyPassword=${FLUTTER_PROD_KEYSTORE_PASSWORD}
          keyAlias=upload
          storeFile=/tmp/upload-keystore.jks
          """ > << parameters.working_directory >>/key.properties

jobs:
  check-android-changelog:
    docker:
      - image: cimg/base:2022.05
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          command: ./scripts/test_changelog.sh
          working_directory: ~/project/mobile_client_app/client_mobile_app

  build-android:
    working_directory: ~/project
    parameters:
      flavor:
        type: enum
        enum: ["dev", "staging", "prod"]
    executor:
      name: android/android-docker
      tag: 2022.09.1
    steps:
      - checkout
      - setup_keystores:
          working_directory: ~/project/mobile_client_app/client_mobile_app/android
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gradle:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_android_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: 
          command: ./scripts/build_android_<<  parameters.flavor >>.sh
          working_directory: ~/project/mobile_client_app/client_mobile_app
      - persist_to_workspace:
          root: ~/project/mobile_client_app/client_mobile_app/workspace
          paths:
            - android/*

  upload-android:
    executor: gcp-cli/google
    steps:
      - attach_workspace:
          at: ~/workspace
      - gcp-cli/initialize:
          gcloud-service-key: TTAC_PROD_GCP_CRED
          google-project-id: TTAC_PROD_ID
      - run: gsutil cp -r ~/workspace/android/* gs://${MOBILE_APP_BUCKET_NAME}/android
  
  release-android:
    working_directory: ~/project
    docker:
      - image: "cimg/base:stable"
    parameters:
      flavor:
        type: enum
        enum: ["staging", "prod"]
    steps:
      - checkout
      - ruby/install:
          version: '3.0.2'
      - ruby/install-deps:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run:
          command: fastlane << parameters.flavor >>
          working_directory: ~/project/mobile_client_app/client_mobile_app

  build-ios:
    working_directory: ~/project
    macos:
      xcode: 13.4.1
    parameters:
      flavor:
        type: enum
        enum: ["dev", "staging", "prod"]
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.1
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_pod:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - flutter/install_ios_gem:
          app-dir: ~/project/mobile_client_app/client_mobile_app
      - run: 
          command: ./scripts/build_ios_<<  parameters.flavor >>.sh
          working_directory: ~/project/mobile_client_app/client_mobile_app
      - persist_to_workspace:
          root: ~/project/mobile_client_app/client_mobile_app/workspace
          paths:
            - ios/*

  upload-ios:
    executor: gcp-cli/google
    steps:
      - attach_workspace:
          at: ~/workspace
      - gcp-cli/initialize:
          gcloud-service-key: TTAC_PROD_GCP_CRED
          google-project-id: TTAC_PROD_ID
      - run: gsutil cp -r ~/workspace/ios/* gs://${MOBILE_APP_BUCKET_NAME}/ios

workflows:
  workflow:
    jobs:
      
      # Android
      - check-android-changelog
      - flutter/unit_test:
          name: "unit_test"
          app-dir: ~/project/mobile_client_app/client_mobile_app
          version: 3.3.1
      - build-android:
          name: "build-android-dev"
          requires: [unit_test, check-android-changelog]
          flavor: dev
          filters:
            branches:
              ignore:
                - "/.*/" # TODO: REMOVE THIS DEBUG CONDITION
                - "master"
                - "dev"
      - build-android:
          name: "build-android-staging"
          requires: [unit_test, check-android-changelog]
          flavor: staging
          # filters:
          #   branches:
          #     only: ["dev"]
      - build-android:
          name: "build-android-prod"
          requires: [unit_test, check-android-changelog]
          flavor: prod
          filters:
            branches:
              only: "master"
      - upload-android:
          requires: [build-android-dev, build-android-staging, build-android-prod]
      - release-android:
          name: "release-android-staging"
          requires: [build-android-staging]
          flavor: staging
          # filters:
          #   branches:
          #     only: ["dev"]
      - release-android:
          name: "release-android-prod"
          requires: [build-android-prod]
          flavor: prod
          filters:
            branches:
              only: ["master"]
      # iOS
      - build-ios:
          name: "build-ios-dev"
          flavor: dev
          filters:
            branches:
              ignore: "master"
      - build-ios:
          name: "build-ios-staging"
          flavor: staging
          filters:
            branches:
              only: "dev"
      - build-ios:
          name: "build-ios-prod"
          flavor: prod
          filters:
            branches:
              only: "master"
      - upload-ios:
          requires: [build-ios-dev, build-ios-staging, build-ios-prod]