- name: Install Processor Input Files
  hosts: processor
  tasks:
    - name: Create var directory
      become: yes
      ansible.builtin.file:
        path: /var/mlab-processor
        state: directory
        mode: '0655'
    - name: Run download_asn_maps.sh
      become: yes
      ansible.builtin.script:
        chdir: /var/mlab-processor
        cmd: ../../../scripts/download_asn_maps.sh
      environment:
        MAXMIND_KEY: "{{ maxmind_key }}"
        TARGET_DIR: /var/mlab-processor/input
    - name: Run download_shapes.sh
      become: yes
      ansible.builtin.script:
        chdir: /var/mlab-processor
        cmd: ../../../scripts/download_shapes.sh
      environment:
        TARGET_DIR: /var/mlab-processor/input
