---
- name: Setup Postgresql Servers
  hosts:
    - postgresql-servers
  roles:
    - monitoring
    - postgresql
  vars:
    postgresql_version: "16"
    postgresql_data_directory: '/mnt/postgresql-data/16/main'
    postgresql_configuration_template: 'postgres.conf.j2'
    postgresql_pg_hba_template: 'pg_hba.conf.j2'
    postgresql_users:
      - name: "{{ postgresql_radar_user }}"
        permissions: "CREATEDB,LOGIN,SUPERUSER"
        password: "{{ postgresql_radar_password }}"
      - name: "grafana"
        permissions: "CREATEDB,LOGIN"
        password: "{{ postgresql_grafana_password }}"
      - name: "prometheus"
        permissions: "LOGIN"
        password: "{{ postgresql_prometheus_password }}"
        groups:
          - pg_read_all_stats
          - pg_monitor
