---
- name: "Generate Password Hash"
  hosts: clickhousedb
  tasks:
    - shell: echo -n "{{ clickhousedb_password }}" | sha256sum | tr -d '-' | tr -d '[:space:]'
      register: db_password_sha256
    - set_fact:
        db_password_sha256={{ db_password_sha256.stdout }}

- name: "Install Clickhouse"
  hosts: clickhousedb
  become: true
  roles:
    - clickhouse
  vars:
    clickhousedb_user: mapping
    clickhouse_path_base: /mnt/clickhouse-data
