---
- name: Setup Postgresql Servers
  hosts:
    - postgresql-servers
  roles:
    - monitoring
    - postgresql
  vars:
    postgresql_version: "16"
    postgresql_data_directory: '/mnt/postgresql-data/16/main'
    postgresql_configuration_template: 'postgres.conf.j2'
    postgresql_pg_hba_template: 'pg_hba.conf.j2'

