---
- hosts: clickhousedb
  become: true
  vars:
    acme_account_email: "devops@exactlylabs.com"
    domain_name: "{{ inventory_hostname }}"
  roles:
    - certbot
  
- name: "Symlinks from LetsEncrypt to Clickhouse"
  hosts: clickhousedb
  tasks:
    
    - name: "Create Clickhouse User"
      become: true
      user:
        authorization: ''
        create_home: false
        name: clickhouse
        group: clickhouse
        password: '*'
        shell: /bin/false
        state: present

    - become: true
      file:
        path: '/etc/letsencrypt/{{ item.path }}'
        state: '{{ item.state }}'
        recurse: '{{ item.recurse }}'
        owner: root
        group: clickhouse
        mode: '{{ item.mode }}'
      loop:
        - {path: "live", state: "directory", recurse: true, mode: '0640'}
        - {path: "live", state: "directory", recurse: false, mode: '0750'}
        - {path: "live/{{ inventory_hostname }}", state: "directory", recurse: false, mode: '0750'}
        - {path: "archive", state: "directory", recurse: true, mode: '0640'}
        - {path: "archive", state: "directory", recurse: false, mode: '0750'}
        - {path: "archive/{{ inventory_hostname }}", state: "directory", recurse: false, mode: '0750'}

- name: "Generate Password Hash"
  hosts: clickhousedb
  tasks:
    - shell: echo -n "{{ db_password }}" | sha256sum | tr -d '-' | tr -d '[:space:]'
      register: db_password_sha256
    - set_fact:
        db_password_sha256={{ db_password_sha256.stdout }}

- name: "Install Clickhouse"
  hosts: clickhousedb
  become: true
  roles:
    - install-clickhouse
