---
# vars file for install-clickhouse
clickhouse_package:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_path_configdir: "/etc/clickhouse-server"
clickhouse_path_logdir: "/var/log/clickhouse-server"
clickhouse_path_data: "{{ clickhouse_path_base }}/clickhouse/"
clickhouse_path_tmp: "{{ clickhouse_path_base }}/clickhouse/tmp/"
clickhouse_service: 'clickhouse-server.service'

# Debian config
clickhouse_repo: "deb https://packages.clickhouse.com/deb stable main"
clickhouse_repo_keyserver: keyserver.ubuntu.com
clickhouse_repo_key: 8919F6BD2B48D754